### ISSUE TITLE
Plethora 1.12.2 crash with Sponge

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#100]
shocking I know, but I got a crash from sponge and plethora. I'm not exactly sure what's going on, but the server either loads, and then lags to its death, or crashes with this error. I'm not even sure if it's plethora's problem but I feel like it would be better if you saw this first, and then directed me to sponge if need be. 
[crash-2018-03-30_06.39.36-server.txt](https://github.com/SquidDev-CC/plethora/files/1864104/crash-2018-03-30_06.39.36-server.txt) Here's the log, it has all the system and server details at the bottom so I won't bother cluttering up this issue report more than need be.

Edit: happy 100th issue/PR!

**Comment by SquidDev** [comment]
```
Description: Watching Server

java.lang.Error

...


Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:62)
	at java.lang.Thread.run(Thread.java:748)

```

This implies that a single tick took 60 seconds to complete, causing the server watchdog to terminate the server. I'm fairly sure this isn't a Sponge or Plethora issue so it might be worth running some profiling tools and playing with Sponge's configs. Sorry :/.

**Comment by hugeblank** [comment]
Alright, thank you! I'll see what I can do.
