### ISSUE TITLE
Audio receiver / microphone (idea)

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev-CC/ccjam-2016#102]
So, we can detect blocks and entities in our close range now,
but what do you think about an audio receiver, or a microphone, if you wish?

It'd be able to receive all sounds in close range (could be basically the player audio range)
and it'd fire an event with the sound properties, distance, etc, so a program could wait for events and using them register sounds. NOT giving the sound location would be nice here, as it'd make for a good audio triangulation. How cool would it be to have multiple microphones on your base to triangulate where that player step sounds are coming from, to detect intruders?
Or you could basically made a subtitling program (which already exists in vanilla minecraft, *subtitling intensifies*)

Feel free to either drop, take, or modify idea to your likings. I'd like to see this in Plethora!

**Comment by SquidDev** [comment]
So I just had a look into this. It's something I'd definitely be interested in doing, but it's sadly not really feasible for two reasons:
 - Some sound events are only played on the client, so you're never going to get all of them.
 - Forge doesn't provide the position of sounds in the event handler, meaning it's impossible to work out where a sound is coming from.

I'm going to close this for now. If this becomes possible with later versions of Forge, it's something I might consider.
