### ISSUE TITLE
Keyboard with touchpad

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/ccjam-2016#108]
I think the keyboard is a genius idea, but I always found it misses the main interaction method you use on your computer; the mouse. Maybe an enhanced keyboard with touch support could be able to give the computer touch events based on where you click when having the keyboard 'UI' open?

**Comment by SquidDev** [comment]
This would probably require integration with the overlay glasses, as mouse events without any idea where you're clicking is pretty useless.

**Comment by Jummit** [comment]
I thought you could maybe lay a grid of the pixels on the computer screen over the screen of the player to find out which pixel on the computer is clicked when the player clicks on his screen. _Hopefully someone can translate this into understandable English._

EDIT:
Image to the rescue!
![grid](https://imgur.com/TBYs7JZ.png "test")

**Comment by SquidDev** [comment]
I can't say I'm a fan of that, as it then means people will have to be counting pixels to make sure they line up. You can't really be rendering a grid on the monitor like that, as you're interacting with the computer, which could have any number of monitors attached.

**Comment by Jummit** [comment]
I just want to use monitors for games, but they are really limited if you can't use mouse. The grid should not be displayed, and you would have to guess, but this isn't for UIs or things where you have to point on very specific area.

The second option would be to still have the normal interaction you can do on a advanced monitor, simply punch it to click. I think computercraft uses the block interact event which gives you the x and y coords of the interaction to find out where the player clicked, but with a little bit of math you could find that out yourself too.
