### ISSUE TITLE
NoClassDefFoundError using overlay glasses addItem in MP

### ISSUE THREAD

**Issue by dmarcuse** [SquidDev-CC/ccjam-2016#110]
When using the code `glasses.canvas().addItem({100, 100}, "minecraft:diamond")` on a server, I get a lua error:
```
Java Exception Thrown: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
```

Other calls (e.g `addText`) work fine.

**Comment by SquidDev** [comment]
That commit is definitely going to break something else. Let's wait and see what :D:.
