### ISSUE TITLE
Zombies unable to fish

### ISSUE THREAD

**Issue by redfast00** [SquidDev-CC/ccjam-2016#116]
I want to set up an automatic fish farm. I equipped a zombie with a neural module (with in it a kinetic augment and an introspection module). I then equipped a fishing rod in it's main hand by using `getEquipment().suck()`. When I then call `.use()`, it says it's succesful, but doesn't cast the fishing rod (there is no bobber).

**Comment by SquidDev** [comment]
Sadly there's nothing I can do about this - the fish hook (or bobber) is hard coded to use players. While we use a fake player, it's only present on the server and so the bobber instantly vanishes on the client side.

**Comment by redfast00** [comment]
So does that mean that the bobber is there and just not visible?

**Comment by SquidDev** [comment]
On the server-side, yes.

**Comment by redfast00** [comment]
Hmm, so nothing stops me from actually fishing with a zombie, right? Will the bobber go down/interact with tripwire? Will mending echantments work?
