### ISSUE TITLE
Enhancement: adapt more abilities of mobs

### ISSUE THREAD

**Issue by redfast00** [SquidDev-CC/ccjam-2016#117]
For example: blazes, shulkers, witches and shulkers have projectiles, they could use the `.shoot()` method.

**Comment by Wendelstein7** [comment]
This would be quite complicated for shulkers, whose projectiles are fired towards a specific entity (their UUID is stored in the projectiles' meta) For blazes, they could just fire in their direction, that would be pretty cool.

**Comment by Lemmmy** [comment]
> their UUID is stored in the projectiles' meta

No reason it couldn't take a string arg instead of two angles I suppose? Or even a separate method for shulkers.

**Comment by shelbykauth** [comment]
`missile()` would make a good shulker method, yeah?

**Comment by SquidDev** [comment]
I'm leaving off shulkers for now, but blazes and witches now have `.shoot` methods of various forms.
