### ISSUE TITLE
Can't make a player shoot arrows with a bow with .use()

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev-CC/ccjam-2016#119]
.shoot() is only available for skeletons, so I tried doing .use() (without arguments) and use([duration]) with various numbers between 1 and 20, yet I can't get a player (myself) to shoot with a bow automatically.

Is this a bug or a feature?

**Comment by SquidDev** [comment]
Ahhh, fantastic GitHub. The duration is measured in ticks, so using 20 should result in the bow being held for 1 second. I've just confirmed this works on a testing world - are you sure you have arrows in your inventory?
