### ISSUE TITLE
Neural Connector Item Loss

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/ccjam-2016#12]
Sometimes, all of the items that have been placed in the Neural Connector disappear.
I believe this somehow correlates to using Creative Mode.

A way to reproduce this 100% of the time is by taking the Neural Interface off of your player, and immediately putting it back on while in Creative Mode.
You will see that the items in the Neural Connector are now gone.

**Comment by SquidDev** [comment]
I'm having issues reproducing. Do you think you could try again with the latest Forge and Plethora versions (even better if you just use this and ComputerCraft)? If it is still broken can you post your logs. Thanks!

**Comment by inklit** [comment]
I'm actually waiting for Sponge to fix issues on their end before I am going to do more testing.
As far as I know though there was no errors or anything out of the ordinary in the log files when I tested this originally.

EDIT:
I tested with Forge 1902 and the latest Plethora compiled from source at the time, SpongeForge, and GriefPrevention.

On that note, there's an issue with SpongeForge's fakeplayer UUID exclusion system which you can see here:
https://github.com/SpongePowered/SpongeForge/issues/804
as well as this issue:
https://github.com/MinecraftPortCentral/GriefPrevention/issues/123
both of which are not issues with Plethora directly, but maybe you will find those issues useful.

**Comment by SquidDev** [comment]
Logs are mostly so I can see other mods/Forge version and so see what might be messing with it. I'm slightly confused why this issue should exist: its the same code as many other mods.

**Comment by inklit** [comment]
See my edit above

**Comment by SquidDev** [comment]
Possibly related to MinecraftForge/MinecraftForge#2523.
