### ISSUE TITLE
Destroyed neural interfaces still executing code

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/ccjam-2016#122]
This may be an issue that only server admins can run into, but it's still probably an issue nonetheless.

I duplicated a neural interface in creative mode, and ran a program on it. Then, I took it out of the helmet slot, and deleted it with the creative inventory slot. It was still visibly executing tasks (seen via prometheus).

`/computercraft view #id` seemed to be booting up a fresh one every time. Shutting down from there just said Goodbye!, then when I re-viewed it, it was booted again.

`/computercraft shutdown #id` said shutdown 1/1 computers, but didn't stop anything.

`/computercraft turn-on #id` said turned on 0/1 computers.

Relogging did nothing - it was still executing while offline.

**Comment by Lemmmy** [comment]
This appears to be part of a larger issue. The player whose neural interface was duped had a wireless keyboard connected to it at the time. My movements in-game (not in GUIs) are captured, and typed on their version of the interface. They can see my `wasd` and `t`.

**Comment by SquidDev** [comment]
I don't think I've seen this again, and there's all sorts of inevitable issues with duping neural interfaces (as they will both link to the same `ServerComputer`), so I'm not sure I can do anything to support it.
