### ISSUE TITLE
Turtles throwing Ender Pearls don't spawn Endermites

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/ccjam-2016#128]
even if it goes through an entire double-chest of enderpearls, zero endermites. While my Neural Interface spamming them gets usually 1 per stack or 2.

**Comment by SquidDev** [comment]
Ender pearls perform several checks when trying to teleport you/spawn an ender pearl:

 - Is the network connection currently open
 - Is the player in the same world
 - Is the player awake (not sleeping)

As turtles require a fake player, their network connection is not considered "open" and so nothing occurs. I suspect any attempt to fix this will introduce even more problems, so I'm going to ignore this for now.

**Comment by ghost** [comment]
Not even doing ASM fuckery to make the first check also pass if it's a turtle?

**Comment by SquidDev** [comment]
Plethora will never be a core mod.
