### ISSUE TITLE
Kinetic augment methods

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#13]
- [x] `walk(x, y, z)` path find to position
- [x] `shoot(x, y, z)` for skeletons with bows
- [x] `swing()` Swing hand to dig/attack (requires fake player)
- [x] `use()` Right click to activate (requires fake player)

**Comment by inklit** [comment]
I don't think pathfinding to a position is a good idea unless there's some sort of hard limit on the calculations that the pathfinding algorithm is allowed to make.
I can see this being abused on my server, for example `walk(9999999, 100, 99999999)`.

If a mob walks towards the edge of a chunk, would it cause the chunks to start loading?
This is another thing I don't particularly think is a good idea, although I can imagine why people would want this.

Aside from those concerns, these seem like good ideas.

**Comment by SquidDev** [comment]
There will be a configurable max distance. I'll have to check chunk loading, though I'm pretty sure it won't.
