### ISSUE TITLE
Thut Wearable Integration 

### ISSUE THREAD

**Issue by freakone20** [SquidDev-CC/ccjam-2016#132]
Got crash when using plethora and thut Wearable, i think it's compatibility issues with thut Wearable mod

https://pastebin.com/BQW4ZJRz

plethora 1.12.2 1.1. 11
forge 2705

**Comment by SquidDev** [comment]
Duplicate of #97. Sorry, I'll try to get an actual release out today for this.

**Comment by freakone20** [comment]
didn't check that out, srry
