### ISSUE TITLE
Module pitch/yaw detection complications

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#133]
I was experimenting with the Introspection Module and the Entity Sensor on a neural interface. I wanted to see which module would be more cut out for some software I'm writing. I ran a test between the both of them that would put a dot on my Overlay Glasses and see which would be more responsive in getting my pitch and yaw. On testing the two I found that the Introspection Module's `getMetaOwner` seemed to be very jumpy and sometimes not responsive at all, whereas by using the Entity Sensor's `sense` and running it through a for loop and conditional to get the two values was significantly faster, more reliable, and less jumpy. I figured I would report this to you considering that the Introspection Module:
A) is a lot harder to craft
B) has `getMetaOwner` which is a lot more convenient than `sense`, and thereby should in theory be faster or equally as fast.
It's also worth noting that I tested both while the server was consistently at 20 TPS, so there was no server-side lag that would have warranted this issue

I was using Switchcraft modpack version 3.14 (_π!_)
Forge: 14.23.4.2739
Plethora 1.1.11
CC: Tweaked: 1.80pr1.6

**Comment by SquidDev** [comment]
Cannot reproduce in a single player world with the following code:

```lua
local p = peripheral.wrap "back"
local g = p.canvas()

g.clear()
g.addText({ 10, 20 }, "sense")
g.addText({ 10, 30 }, "getMetaOwner")

local sense        = g.addText({ 90, 20 }, "")
local getMetaOwner = g.addText({ 90, 30 }, "")

parallel.waitForAny(function()
  while true do
    local meta = p.getMetaOwner()
    getMetaOwner.setText(("%s, %s"):format(meta.pitch, meta.yaw))
  end
end, function()
  while true do
    local meta = p.sense()[1]
    sense.setText(("%s, %s"):format(meta.pitch, meta.yaw))
  end
end)
```

The two values appear to be entirely in sync with each other.

**Comment by Lemmmy** [comment]
This would likely be because of the energy differences on SwitchCraft.

**Comment by Lemmmy** [comment]
@hugeblank Yemmel and I made a few changes; the two methods should be entirely equivalent now.

**Comment by SquidDev** [comment]
@Lemmmy Thanks for the information!

**Comment by hugeblank** [comment]
Thanks @Lemmmy much appreciated :)
