### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by codeka** [SquidDev-CC/ccjam-2016#134]
Can we possibly get a new release of plethora? I've been trying it out (and loving it!), but I needed to compile it manually from master to get the fix in https://github.com/SquidDev-CC/plethora/commit/ab6396a7343718523bff51ff8f7e6baad22e6bb3, it would be nice if I could just just get a proper release :)

**Comment by codeka** [comment]
\o/ thanks!

**Comment by SquidDev** [comment]
No worries - sorry for stupidly long delay between bug fix and release.
