### ISSUE TITLE
Add a way to unbind introspection modules

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/ccjam-2016#137]
Players are often complaining when installing artist that they aren't able to unbind their already bound introspection modules. Perhaps shift+clicking the air again should unbind it?

To make the interface more friendly, you could perhaps popup some text above the hotbar (same text as swapping item) or in the chat saying "Bound introspection module to Lemmmy", "Unbound introspection module"

**Comment by SquidDev** [comment]
I forget that Minecraft makes it very easy to push "toast" notifications to the hotbar now. Yeah, this should be pretty easy to do.

**Comment by Lemmmy** [comment]
Thank you! <3
