### ISSUE TITLE
[Feature Request] Overlay Glasses setOrigin(x,y,z)

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/ccjam-2016#146]
It would be cool to have some function to set the origin point of the canvas3d like `setOrigin (x, y, z)` in addition to the function `recenter()` because with this we could set the same origin for the canvas3d across different neurals interfaces to make everyone see the same elements at the same places and not only relative to were we created the canvas3d

**Comment by SquidDev** [comment]
I don't want to allow the user to provide absolute coordinates, as the main rationale behind the current design was to avoid leaking values. It would definitely be possible to accept relative coordinates though - as returned by the entity sensor and friends.

**Comment by Shiranuit** [comment]
Seems to be a good compromise to me

**Comment by SquidDev** [comment]
Thank you very much for the suggestion!
