### ISSUE TITLE
.getBaubles() method not working

### ISSUE THREAD

**Issue by Wr1nGl** [SquidDev-CC/ccjam-2016#147]
I am playing on dw20 1.12.2 and for some reason i cant use that method. Same for .addGroup(). Tried it in neural interface with the correct module installed. Tested on Plethora version 1.1.11 and 1.1.12.

**Comment by Lemmmy** [comment]
What do you mean by "can't use"? Does the method not exist? Do you get a Java error?

**Comment by Wr1nGl** [comment]
Sorry, for the bauble method, it is not offered when i am in lua for testing purposes and when i try to call it I get nill error, so i pressume it doesnt exist. I get nill error for the group method as well.
