### ISSUE TITLE
Allow Accessing Output Slot of Crafting-type Inventories

### ISSUE THREAD

**Issue by shelbykauth** [SquidDev-CC/ccjam-2016#148]
Enhancement Request

## The Issue
Crafting-inventory peripherals, such as the Tinker's Construct benches, don't allow grabbing of the output items.

For an inventoried crafting table, the size reads as 9.  Meaning the nine input slots.  Currently there's no way to access the last slot (the output slot).  Now for crafting tables, this makes sense, just put the items in a crafty turtle.  However, for other things like the Tinker's Construct stuff, bibliocraft and storageDrawers panellers, etc, there's no way to automate the crafting and customization of things like a TConstruct tool or panelled furniture.

## Possible Solutions
I can think of two ways to go about this, in terms of lua code.  One, add an extra slot to the inventory which you can not push too and can only pull from.  And pulling from that slot does the output thing.  Or do something with the inner inventory thing that I'm still not very clear on.  Two, add a method to the peripheral called... "getOutput()" maybe?  and "pushOutput()".  I prefer the other way, of adding slots.  Though it needs to be marked differently or something.  So maybe an extra method called outputSlots(), which gives you a list of output slots.

I don't know how this would be done in terms of Java code.  I know that there's a way to see the output before actually grabbing it, because it shows up in the UI.  I know there's a difference between permanent outputs, like the furnace, and non-permanent outputs, like the tool station.  Currently the permanent outputs are accessible, but the non-permanent are not.

## Use Case
As to the benefit this would provide and use cases.  I think it's pretty clear, but in case it's not.  One of my ideas is an automated TConstruct shop where you go up to the main computer and select what you want to purchase, and you can customize your tool, like a pickaxe with a wooden handle, an obsidian head, an iron crossbar, and 50 redstone and a diamond applied to it.  The computer system then drains some iron and then obsidian out of its main tank and casts the head and crossbar (It can do this now, thank you very much for that.)  And it crafts a wooden handle at the part builder, then sends all the parts to the right locations in the tool station and takes the finished product from the table and spits it out at the trading chest.

## Side Note
By the way, as an irrelevant side note, I love how you can make the chests spit items out and suck items up.  This makes it so you can go into an area where you're not allowed to interact with anything (WorldGuard, Towny, FTBUtils, or any other protection plugins/mods) and using either pressure plates, chat listeners, a wireless pocket computer, etc, purchase things from a player-made shop in that area.  And it makes for a really cool Turtle Bartender.

**Comment by SquidDev** [comment]
> For an inventoried crafting table, the size reads as 9. Meaning the nine input slots. Currently there's no way to access the last slot (the output slot). 

> I know that there's a way to see the output before actually grabbing it, because it shows up in the UI.

This would definitely be useful, but the above is pretty much the crux of the issue. The slot doesn't actually exist in the inventory at all - it's _only_ in the UI. 

It's definitely possible to emulate this, but I'm not quite sure how much messing around within internals this takes. I don't think you can sensibly fake opening a container, so the most sane implementation here is probably going to be handling each block on a case-by-case basis.

I'll have a look over the next few and see if it's feasible. I'm not sure quite how much messing around with Tinkers' internals this'll require, so I'm afraid I can't promise anything quite yet!

**Comment by shelbykauth** [comment]
Okay.  I was thinking you could use whatever methods the UI uses to see and grab the outputs.  And it was a toss up (in my mind) as to whether that was standardized or coded uniquely per mod.  I was really hoping it was standardized.

Thanks for looking into it.  I appreciate all the hard work you put into this.
