### ISSUE TITLE
[Rendering Issue] Overlay Glasses Box faces rendering

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/ccjam-2016#153]
Sorry for giving you so much work

When you place some boxes each one next to the others with no transparency and then you're facing a certain direction the drawing order of the boxes faces is wrong

- [x] Minecraft 1.12.2
- [x] Forge 14.23.4.2730
- [x] Plethora 1.1.12 [Latest Sources ?]

West:
![image](https://user-images.githubusercontent.com/19224148/43853609-f47459a4-9b40-11e8-9ad8-a54c0c2343d0.png)
East:
![image](https://user-images.githubusercontent.com/19224148/43853628-009fc344-9b41-11e8-9bb3-3aedc1a6ef7f.png)
North:
![image](https://user-images.githubusercontent.com/19224148/43853753-4ac41858-9b41-11e8-9999-9447350b8d40.png)
South:
![image](https://user-images.githubusercontent.com/19224148/43853781-5a596bba-9b41-11e8-8c35-17dda6638fe9.png)
Up:
![image](https://user-images.githubusercontent.com/19224148/43853808-6e25ba5e-9b41-11e8-871a-f0123cb1a313.png)
Down:
![image](https://user-images.githubusercontent.com/19224148/43853824-7b79c0a6-9b41-11e8-9d18-609c51d23e07.png)

**Comment by SquidDev** [comment]
> Sorry for giving you so much work

No worries! I'd rather the bugs were reported than me being unaware of them.
