### ISSUE TITLE
[Issue] Entity Sensor [Multiplayer] [MC1.12.2]

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/ccjam-2016#154]
Hi, there is a new issue in multiplayer with the Entity Sensor module
- [x] Minecraft 1.12.2
- [x] Forge 14.23.4.2730
- [x] Plethora 1.1.12
- These methods `getMetaOwner`, `getMetaByName` and `getMetaByID` return an empty table `{}`
- `sense` throw a java error : 
![image](https://user-images.githubusercontent.com/19224148/43923693-c16c4944-9c22-11e8-9f87-f341e89b61ea.png)

**Comment by SquidDev** [comment]
Can you attach your logs please (the server logs that is).

**Comment by SquidDev** [comment]
Fixed in 807240e835a028bb548a9a1be6b886f8311d41bd.
