### ISSUE TITLE
Can't read from EnderIO machines.

### ISSUE THREAD

**Issue by BigCasper** [SquidDev-CC/ccjam-2016#155]
Computers can't read energy data from EnderIO Capacitor Banks, like they can from IC2 power storage options.
EDIT: checked most machines from EnderIO, there are no methods to get power or progress. You can read power from EnderIO items in your inventory.

**Comment by SquidDev** [comment]
There's sadly not a lot I can do here, as EnderIO don't seem to follow the norm when it comes to capabilities. I'll raise an issue on their tracker.

**Comment by Jummit** [comment]
That's kinda sad, as EnderIO is one of my favorite mods (I wanted to make a program that displays energy generation and consumption). Can you link me the issue in EnderIOs repo? (Just for reference, to see if something is in the works)

**Comment by SquidDev** [comment]
To be honest, I can't quite remember why EnderIO doesn't work - not sure what I was referring to when saying they did capabilities differently.
