### ISSUE TITLE
Neural Interface not rendering with Baubles

### ISSUE THREAD

**Issue by BigCasper** [SquidDev-CC/ccjam-2016#156]
It is possible to wear the Neural Interface in the head bauble slot with Baubles installed and have it execute code properly. It doesn't render the model on the Players head though. Minor thing, but still would be nice to have it visible in TPV.

**Comment by dmarcuse** [comment]
It should be visible, there [was a bug which was fixed a while ago](https://github.com/SquidDev-CC/plethora/commit/23802cf5d2a2562178d80a4f7577785efb530418) that prevented it from working. Which version are you using?

**Comment by BigCasper** [comment]
1.1.12 (latest at 21 August 01:40 UTC +2 on Curseforge)

**Comment by dmarcuse** [comment]
I can't reproduce this issue, what mods/versions are you using? Anything in the logs?

![2018-08-20_21 58 22](https://user-images.githubusercontent.com/5429337/44375945-48662880-a4c4-11e8-882e-a9d9598301b8.png)

**Comment by BigCasper** [comment]
I'll post the modpack soon, and in the server logs or client logs (reproducible on my machine in both) nothing of importance.

**Comment by BigCasper** [comment]
The fault for this is on my and my config tweaking. Everything is working properly, and it renders after some more config tweaking. Sorry, please close.
