### ISSUE TITLE
Advanced Rocketry Support

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/ccjam-2016#160]
Blocks:

- [ ] Rocket Assembling Machine (Read the rockets stats after building, read error/success message)
- [ ] Monitoring Station (Read how high the rocket is, how much fuel it has left, how fast it is going and the mission progress)
- [ ] Satellite Builder (write to secondary chip function)
- [ ] Guidance Computer Access Hatch (set ejection on landing settings and the destination, and disassemble)
- [ ] Observatory (Get observable view distance, get the amount of data, find asteroids, get the composition and scan them)
- [ ] Planet Selector (Get the solar systems and planet information, and select planets)
- [ ] Satellite Terminal (Connect to satellites, read the data, energy production and storage and what they have as sensor)
- [ ] Astrobody Data Processor (Toggle research, get research progress, store data to buffer or in chip)

**Comment by SquidDev** [comment]
Closing for the same reason as #158. If people need integration with AR, feel free to create a new issue/comment here detailing exactly what you'd like to see.
