### ISSUE TITLE
Manipulator with bound introspection module unusable after logout

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#167]
When logging out / logging into the Switchcraft server, calling getName on a manipulator with a bound introspection module errors with "Entity is no longer there".

This occurs occasionally for some players and all the time for Drucifer. Rebooting the computer has no effect. The only way to get around the error (that I know of) is to remove the bound introspection module and replace it.

In further testing, any function on the manipulator returns the same error (even getDocs). On a MkII equipped with a block scanner, calling scan also returns the same error.

**Comment by fatboychummy** [comment]
It's not the action of logging out or in that causes this.

When you die, the introspection module (and all other bound modules) will be bound to your dead entity, which is "no longer there"

I've never had this problem after a relog

**Comment by kepler155c** [comment]
In the following screenshot, I logged out/back in after the first getID() call.

![screenshot from 2018-11-26 16-22-22](https://user-images.githubusercontent.com/16342516/49043000-babb6880-f197-11e8-8db3-ddc45f698517.png)

**Comment by SquidDev** [comment]
Probably related to #104, though I'd need to double check. I thought I had fixed all references which directly depended on the entity, but evidently not.

**Comment by kepler155c** [comment]
Have you fixed this issue on the Switchcraft server? I have not seen the error in a few days.

**Comment by SquidDev** [comment]
This has been partially fixed in 9d2bd6780ac65b4f5c3489d617603e5107222e29 (which is now running on SC), but there's definitely some additional changes which need to be made in order to prevent this and similar issues occurring again.
