### ISSUE TITLE
change order of drawing for overlay glasses not working

### ISSUE THREAD

**Issue by Neywiny** [SquidDev-CC/ccjam-2016#168]
According to #95 the last drawn object is in front, but from what I can tell from my code that is not the case.
```
canvas = peripheral.wrap("back").canvas()
canvas.clear()
storageGroup = canvas.addGroup({0,0})
grid = {{{{},{}},{{},{}},{{},{}},{{},{}}},{{{},{}},{{},{}},{{},{}},{{},{}}},{{{},{}},{{},{}},{{},{}},{{},{}}},{{{},{}},{{},{}},{{},{}},{{},{}}}}
for i = 1,4 do
	for y = 1,4 do
		grid[i][y][2] = storageGroup.addText({(i-1) * 16, (y-1) * 16 + 8},"4")
		grid[i][y][1] = storageGroup.addItem({(i-1) * 16, (y-1) * 16}, "minecraft:stone",0)
		return
	end
end
```
(note that return just so the rest of the program doesn't run until I fix this issues)
Changing the order of drawing by switching the lines does nothing. Ideally I'd be able to set a Z position but it seems like that is not supported yet.

**Comment by SquidDev** [comment]
I have a feeling this is an issue exclusive to `.addItem`. This is technically a 3D object, and will not be sorted correctly, like other items are. I'll have a look into ways of fixing this.

**Comment by Neywiny** [comment]
thanks for the speedy reply, good luck. In the mean time I'll draw a clunky UI with text under the items.
