### ISSUE TITLE
Refined Storage Integration

### ISSUE THREAD

**Issue by NielsPilgaard** [SquidDev-CC/ccjam-2016#169]
## Useful information to include:
 - Minecraft version
1.12.2
 - CC: Tweaked version
1.80pr1.11
- Refined Storage version
1.6.9
 - Detailed reproduction steps!** Sometimes I can spot a bug pretty easily, but often it's much more obscure. Anything you can give which will help reproduce it means it'll get fixed quicker.
Put down a Refined Storage controller and Refined Storage Crafter, and power them. I believe that should do the trick.

Refined Storage has changed the way autocrafting is handled internally, so the support needs updating, I think.
### Log: ###
https://gist.githubusercontent.com/NillerMedDild/f8d489d7aa12d45fc03f8952dafb3b1e/raw/ed9b40302d94dca9b5110f96c5cf038fa4307b95/gistfile1.txt

Note that the paste is truncated.

**Comment by NielsPilgaard** [comment]
Thanks :D

**Comment by SquidDev** [comment]
No worries. Sorry it took so long to get to!
