### ISSUE TITLE
Modems work oddly with things connected directly to a computer

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/ccjam-2016#170]
So the error occurs when you have the computer you are working from with a peripheral attached directly to it (chest, manipulator, anything really), and then a modem storage network connected on the other side.

Here's an example:

![image](https://user-images.githubusercontent.com/39929480/49681653-e9242800-fa62-11e8-8fbe-699bba2bd522.png)

If I try to pull an item from the chest directly connected to the computer, it will work fine.  However, if I try to pull an item from the chest connected to the modem?  Error. (`Lua:1: Source "chestNameFromModem" does not exist`)

Another example;  Try to move items from chest 1 at the bottom left to chest 2 on the modem.  Also error.

This used to work (without errors) in an older version (Running Switchcraft).
Old CC:Tweaked Version: 1.80pr1.7-hard-times
Old Plethora Version: 1.12.2-1.1.12-forbidden-friendship

The new version of the pack, however, does not work
CC:Tweaked Version: 1.80pr1.10-the-idiot
Plethora Version: 1.12.2-1.1.13

I can work around this for now, but thought I might let you know

**Comment by fatboychummy** [comment]
![image](https://user-images.githubusercontent.com/39929480/49681576-87af8980-fa61-11e8-9657-5b46ff2ba883.png)

**Comment by SquidDev** [comment]
I'm fairly sure this behaviour is intentional. Each side of the computer is an entirely distinct "network", and shouldn't even be able to see each other. 

Than said, it's curious that it worked on older versions. I can't think of anything which changed in the codebase, so I'll have to do a little more testing.
