### ISSUE TITLE
Modification to the Frickin' Laser Beam

### ISSUE THREAD

**Issue by sorucoder** [SquidDev-CC/ccjam-2016#171]
Using shift-right-click to switch "modes": By default it should damage only mobs, shift-right-click once to damage only blocks, and shift-right-click to do both.

Accomplished in code running `laser.switchMode()`

**Comment by SquidDev** [comment]
I'm rather reluctant to do something like this, as I'll get onto in a moment, but this has come up a couple of times, so I'll leave this open to allow others to chip in with their comments.

From an in-universe perspective, I'm really not sure the idea of modes makes sense. While [it's ambiguous](https://squiddev-cc.github.io/plethora/items/module-laser.html) how the laser works, it shouldn't be selective in it's destruction - it doesn't care if something is an entity or a block, it'll keep going until it runs something it can't kill.

Out-of-universe, I'm rather worried about allow this, as you're meant to think about how to minimise the unwanted damage the laser will do. It's _meant_ to be unforgiving in the damage it'll do, so you can't just plonk down a laser sentry next to your base, as it'll quite happily destroy everything.

There's obviously ways to design systems which do minimise damage: fire low potency blasts, which won't destroy most blocks; clamp the angles the laser will fire at, so it's not going to fire at the ground, etc... But the point is you've got to think about it first.

**Comment by sorucoder** [comment]
Well the inspiration for this particular idea comes from Cyborg 009 - which has different laser modes. See [this](https://cyborg009.fandom.com/wiki/Super_Gun). But what about different laser types - ones that paralyze entities?
