### ISSUE TITLE
Refined storage export error

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#175]
Minecraft: 1.12.2
Refined storage:  refinedstorage-1.6.5.jar
cc: cc-tweaked-1.80pr1.12.jar (from dropbox)
plethora: plethora-1.12.2-1.1.13.jar

When invoking export on an item found (using the interface), I get the following error:

![screenshot from 2019-01-07 11-43-58](https://user-images.githubusercontent.com/16342516/50781490-7da4c480-1273-11e9-9fd3-0a872a9f9af5.png)

Listing items works as expected.

**Comment by SquidDev** [comment]
Probably fixed in ea01b33b1cb4178a93c93d0933e47b7bca789260, but I'd need to check.

**Comment by SquidDev** [comment]
Can confirm it has been fixed.

**Comment by kepler155c** [comment]
Working great - thanks
