### ISSUE TITLE
Server crash from A Frickin' laser (projectiles), reproducible, 1.12.2

### ISSUE THREAD

**Issue by SillyPutty** [SquidDev-CC/ccjam-2016#176]
I'm running a small server with a bunch of mods featuring cc-tweaked and plethora, and found a bug that managed to crash the server related to lasers. When firing a large number of laser shots from a neural implant horizontally off into the distance, the projectiles can get stored into unloaded chunks, and cause a server crash if/when those chunks are loaded at a later time. After rebooting the server, loading those chunks will repeatedly crash the server unless the laser projectiles are manually removed from the region data file. I was able to repeat the crash by shooting about a hundred or so lasers. After the crash I checked and had to delete 6 laser projectile entries from the chunk's entity list before the server was stable again.

Relevant mod versions:
forge-1.12.2-14.23.5.2796-universal.jar
cc-tweaked-1.80pr1.8.jar
plethora-1.12.2-1.1.13.jar

Here's one of the server crash reports: [https://pastebin.com/jjptL2kZ](https://pastebin.com/jjptL2kZ)

**Comment by SquidDev** [comment]
Right, this appears to have been a weird interaction between MinecraftForge/MinecraftForge@c20a5e8805f64097430cf0722011f20862a8df9c and Plethora. 

I've put together a [hopefully fixed version](https://www.dropbox.com/s/de5e1ghj80qm7he/plethora-1.12.2-1.1.13-world-npe.jar?dl=1) - can you run it and confirm it fixes your problem?

**Comment by SillyPutty** [comment]
I believe the new version fixed the problem!
