### ISSUE TITLE
Creative Introspection Module

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#178]
< tmi > 
I'm working on a project that uses a command computer in tandem with a creative chat recorder in order to interact with the user via tellraw and stuff ([this](https://github.com/hugeblank/Allium) if you care <3). I came across a speedbump in the development of this utility when it came to getting the player's position. I used the tried and true armor stand strategy, however in order for the armor stand to be teleported to the player, gather the coordinates, and then teleport it back to its 'base' location 3 ticks are expended. This speed isn't exactly optimal considering I want to be able to run anything I throw at the utility with as little delay as possible with as little reliance on multithreading commands as possible. Thus:
< /tmi >

The creative introspection module would do all the same things that a regular introspection module could do, however instead of needing to shift+right click to bind to a player, a method `.bind` is added, requiring the name of the player that is to be bound to, and returning a table containing all of the methods that a good ol' bound introspection module would provide. Not only would this solve my problem in 0 ticks, but allow for much more data than my current solution to be extrapolated from a player.

**Comment by SquidDev** [comment]
As far as the tmi section goes, it shouldn't take three ticks (fairly sure you can execute all in one tick), and I don't _think_ you need to do back-and-forth teleporting. [This is what I used in taken][taken], and it seemed to work OK. That said, no clue how it plays when you've got things which don't check for invisible entities.

As far as the actual suggestion goes, I'll have to have a think about it. I'm a bit reluctant to add any more "creative" modules, as server management really isn't the aim of Plethora (and this be more complicated to implement than the creative chat one). However, I can definitely see how it'd be useful.

One thing to note, you could technically spawn in introspection modules for each of the players using a command computer, but then using those modules would be much more painful.

[taken]: https://github.com/SquidDev-CC/Taken-Map/blob/6c8c1f6ade99b9b57f5d28c1ef6a30901680d024/server/player.lua#L62-L69

**Comment by hugeblank** [comment]
Now that you mention it, I am doing it in one tick but the method you use is better. Having it done in one tick is great and all, but the introspection module allows a much more direct access to the position of the player, and other *really* useful data.

I know the aim of both CC and Plethora isn't for server management, and I think that part of the fun in my project is to try and make a viable server scale plugin solution using what's contained within CC and Plethora. I figured I would propose this because it may actually be useful beyond my endeavor and I can't imagine that it would disrupt the structure of the introspection module within the mod.

**Comment by SquidDev** [comment]
It might be possible to do some command computer API, which exposes some server-wide entity + introspection sensor, but I'm not convinced right now.
