### ISSUE TITLE
Ender Entity Sensor

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev-CC/ccjam-2016#181]
So I'm wondering, what if I wanted to have a large radar scanning my house for intruding entities?
I'd have to place an entity scanner every 16 blocks in every axis, so the place would become really crowded with scanners.

What's your opinion on an ender sensor? An more expensive version of the normal entity sensor, whith perhaps like 4 times the radius of the normal entity sensor (so that'd mean 32 blocks in all directions, or two chunks)

I am aware that the radius of normal sensors are tweakable, however for obvious reasons you might want to keep the normal sensor at it's default for balance, server performance or both...

Give it a thought!

Perhaps introduce a nether star as expensive-making radar thingy, if you're seeking how to make it balanced yet powerful

With love,
~Hydro

**Comment by Lemmmy** [comment]
I could imagine this could incur some chunk-related issues given the fact that they would be spanning a large number of chunks given your specifications. Just a quick thought.

**Comment by SquidDev** [comment]
From Slack, 

> Alternative idea: Every additional nether star increases the distance by `max_range/level`. So you'd go 16 -> 32 -> 48 -> 56, etc...

Then we can just chuck an enchant glint and lore text on it, instead of a whole new module. 

I think the cost of calling `scan`/`sense` also scale by the level or volume, so you can't call it quite as frequently as a base one. Ideally a large volume should never be more than once per second.
