### ISSUE TITLE
Gendustry Industrial Apiaries Not Recognized

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#183]
In a modified version of Stoneblock (mod list available at http://www.modlister.com/user/nerdpie/StoneBlock ), Gendustry's Industrial Apiaries don't appear to be recognized as peripherals, even though a cursory look at your code, particularly https://github.com/SquidDev-CC/plethora/blob/minecraft-1.12/src/main/java/org/squiddev/plethora/integration/forestry/MethodsBeeHousing.java#L11 , seems like they should show up.  I haven't delved into the reflection 'black magic' used by Plethora or OpenComputers, but they also appear to base compatibility off of the IBeeHousing interface, and theirs worked, at least in Modern Skyblock 3, so I'm not sure where the issue is.  At a more basic level, it is peculiar that the Industrial Apiary isn't even recognized as an inventory, though I haven't checked which inventory technique they are using (e.g. the old interfaces, capabilities, or both). </wall_o_text>

![2019-02-22_12 27 44](https://user-images.githubusercontent.com/11985331/53339485-bdcc0f00-38d4-11e9-9818-0f83cc5b5fe3.png)
![2019-02-22_12 27 46](https://user-images.githubusercontent.com/11985331/53339486-7e052780-38d4-11e9-857d-3e8fdf90f066.png)

Side note: It threw me off a bit that Psi's Conjured Light is recognized as a peripheral...

**Comment by SquidDev** [comment]
See bdew/bdlib#49. However, this has happened enough times it's probably worth me adding an override on my end.
