### ISSUE TITLE
Roost Support

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#184]
I would like to see support for the Roost mod, namely exposing the growth/gain/strength stats of the chicken items.  If possible, a means of getting the breeding tables would be useful as well, though the config JSONs could be parsed as a fallback in players' Lua code.

Parts
- [ ] [ItemChicken](https://github.com/timrwood/roost/blob/master/src/main/java/com/timwoodcreates/roost/item/ItemChicken.java) stats
- [ ] Breeder - May be the best spot to add a method for the breeding tables, if desired.  Otherwise, the inventory is already wrapped properly.
- [ ] Roost - Inventory is already exposed properly.  I don't know of any additional functionality needed, unless convenience methods such as 'hasSeeds' are desired.
- [ ] Roost Collector - Effectively a ranged hopper; I haven't tested it, but I suspect that its inventory is also properly exposed.

Having glanced at the Roost code, it appears that the breeding data is pulled directly from the Chickens mod (see https://github.com/timrwood/roost/blob/master/src/main/java/com/timwoodcreates/roost/data/DataChickenModded.java#L27 ).  While I imagine some would like support for Chickens/Hatchery, the involvement of entities would greatly complicate automation, hence my focus on Roost.

**Comment by Lemmmy** [comment]
PRs welcome

**Comment by plt-amy** [comment]
PRs welcome

**Comment by Nerdpie** [comment]
@SquidDev If you want, I could take a crack at the code, though I would want to make sure that I follow the design patterns you are already using.  When I looked at the Forestry integration (closest existing functionality, at least at a glance), I had a little trouble following the structure, though that may have been because I was up late, and Forestry's integration is necessarily more complex...

**Comment by Nerdpie** [comment]
I'm currently working on making IDEA settle down a bit (I have the inspection thumbscrews turned tight; I prefer it to tell me before I break things), but I am unusually driven to figure out the Roost integration.  A less settings-related issue with IDEA is that it doesn't seem to be parsing the build.gradle properly, at least in terms of recognizing the plugins and references to gradle.properties...

I think I have a decent grasp on how the annotations are used for dynamic run-time loading of methods, though one piece eludes me: how to handle multi-mod interactions.  In this particular case, Roost's "DataChickenModded' is annotated as 'Optional', depending upon the presence of the Chickens mod; without Chickens, Roost appears to only add an item version of the vanilla chicken.  While I suspect that most, if not all (dev environments notwithstanding) users will have Chickens alongside of Roost, we all know the saying about assumptions...

... actually, looking closer, I should be able to use Roost's "DataChicken" class, as both DataChickenVanilla and DataChickenModded extend that class, and it specifies all of the methods for getting a chicken's stats, parents, and a method to get all registered chickens.  I may have fallen too far into the rabbit hole...

And while I was waiting to post this, I realized that behavior with generics in Java can be a bit 'iffy'; depending upon how the methods are injected, it may just call the base class' methods rather than those of the extending classes.  Rather than me thinking in circles, is there a way that I can contact you for more real-time chat, @SquidDev ?  Discord perhaps?

**Comment by SquidDev** [comment]
Thank you for looking into this. I really appreciate it <3.

> I had a little trouble following the structure, though that may have been because I was up late, and Forestry's integration is necessarily more complex...

Forestry is a little messy due to how much info it exposes but nah, everything in this mod is just over-engineered and depends on magic annotations. I love it, but oh goodness ~~some things~~ everything needs a rewrite.

> I'm currently working on making IDEA settle down a bit (I have the inspection thumbscrews turned tight; I prefer it to tell me before I break things)

Mine are pretty close to the default, and even then IDEA screams blue murder. Partly because some code probably hasn't changed since Minecraft 1.8.9, and so is pretty terrible, and partly because I'm paranoid and have a load of `null` checks even when things are marked `@Nonnull`.

> is there a way that I can contact you for more real-time chat

I'm `SquidDev` on espernet and freenode and `SquidDev#8925` on Discord. If you can't find me, probably easier to [join this server](https://discord.gg/H2UyJXe) and message me from there.

**Comment by SquidDev** [comment]
I _think_ this can be closed now.
