### ISSUE TITLE
GitHub Page Minor Fix

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#187]
I made a fork of the project so that, first, I could make a PR for a couple of minor issues on the 'Ore Scanner' example.  Not having used GitHub Pages before, I didn't know whether the build.lua script was run automatically; having made the change in the base ore-scanner.lua file, I now realize that it is not automatic.  For the sake of consistency, what version of Lua do you have installed for that file?  Alternatively, if you prefer, the commit is https://github.com/Nerdpie/plethora/commit/a302e15c67265cc05641fce2d9e49e5277c2b81f .

The main functional change is in the 'render' function; when I used the original code, it appeared to rotate such that South was 'up' on my screen.

**Comment by SquidDev** [comment]
I've just merged that in - thank you very much for the fix!

It should work with any recent Lua version - I've just tested on 5.1 and 5.3 and not had issues. It'd definitely be nicer if the whole thing was automated, but I'm not sure that's possible given how GH pages works (well, without doing some serious Jekyll wizardry).
