### ISSUE TITLE
Turtle minecarts

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#188]
Allow turtles to be placed in minecarts (or add storage to existing computer minecarts) allowing for moving items over distances. Would need the ability to wrap peripherals at stopping points (or hopper items in/out).

**Comment by SquidDev** [comment]
It's not something I have any interest in implementing myself, as the implementation will be very complex, but I'm definitely open to someone submitting a PR.

**Comment by Nerdpie** [comment]
I haven't checked the existing functionality (e.g. if the Entity Sensor can see the contents of a hopper minecart), but the basic Minecart Computer with the Kinetic Augment _may_ be able to fill in for this behavior.  Basically, use a Minecart Computer to push the inventory minecart, and have a partner computer at your 'stations' to control powered rails and the loader/unloader mechanism of your choice.
Caveats:
- Subject to entity collision bugs - the Minecart Computer may be able to clip through the cart that it is intended to push
- Chunkloading - Practically goes without saying in modded, but chunkloading may cause extra fun, e.g. the pushed cart entering an unloaded chunk...
- Ignores all mod interactions, such as Railcraft train building or Signals-mod (by MineMaarten, I think?) signal blocks/stations/carts.

Side note: At this time I do not personally have interest in implementing Railcraft or Signals integration.

**Comment by kepler155c** [comment]
Ignore -
