### ISSUE TITLE
Disable AI improvements

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#19]
It currently just disables all physics. Could we:
- Change this to be a toggle method?
- Clear the AI task list instead/suppress the AI
  - How would this work with `.walk` (see #13)
  - Could we restore them: allow toggling AI?

**Comment by nevercast** [comment]
@SquidDev This is permanent, could it be a toggle? I see that mentioned in the OP but that is not how it is implemented. Any reason it was not made to be a toggle? 

**Edit:**
After looking at the code, this seems quite easy to implement. I'd be happy to PR this if I find the time this week, any objections?

**Comment by SquidDev** [comment]
I'm always open to PRs, so if you're willing to look into it, that'd be great! 

However, from what I remember it does end up being quite tricky. We clear the AI task lisk and there's no way to get it back. You'd most likely need to create a new instance of that entity, or re-add all cleared tasks back. Not sure if that'd cause issues with mobs which often add new tasks to the list though... 

Ugh, this feature has always been a hack. Wish there was a nicer way to implement it, but I suspect any other method relies on core mods :/.

**Comment by nevercast** [comment]
s/bombs/mods/  ?

**Comment by SquidDev** [comment]
Mobs even. Should know better than to respond to issues on mobile.

**Comment by nevercast** [comment]
I gave this some more thought, why not create our own AITask that never exits on its own, set that to highest priority, and add the task just executes the Kinetic instructions?

When we want to return the AI, we just deque our task

**Comment by nevercast** [comment]
We implement `EntityAIBase` that *shouldExecute*, *shouldContinueExecuting* and is **not** *isInterruptible*. That does whatever it needs, I guess at minimum it can probably do nothing and that serves as our "dumb slave" logic for `disableAI()`, and in the future we could implement the kinetic logic in there if it makes it simplier.

**Comment by nevercast** [comment]
I can't work on this tonight but if you're not done by tomorrow (because I know you're speedy), I'll get started on making a PR for this feature.

**Comment by SquidDev** [comment]
Had a very quick look, and it looks like it might work. I'm afraid I haven't really looked at this area of the code since I wrote it (2 years! How has time gone so quickly), so can't really comment on anything in too much details.

If you want to have a crack at it, that would be fantastic. I'm part way through exams right now, so am really only having a look at the easy issues.

**Comment by nevercast** [comment]
Yep, should get some time tomorrow to look at it.
