### ISSUE TITLE
Astral Sorcery Support

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#190]
Watching Dire derp on stream, I thought that it would be handy if the stats for Astral Sorcery's crystals were exposed in programs.  I do not know if any other functionality would be desired.  I will work on this once I've finished #184 .

-----------
Edit:

Potential integrations:
- [x] Constellation Paper - Constellation name
- [x] Crystal Properties - Refers to the size, purity, and cutting of crystals, as well as many items crafted from them
- [x] Constellation Attunement - Item meta, player meta; check if other entities can be attuned
- [x] Astral Tome - Stored constellation papers
- [ ] Looking Glass, Telescope, Observatory - Might report the constellations in the sky each night
- [ ] Fosic Resonator - Provide info about the starlight in an area
- [ ] Resonating Wand - Should already work to trigger crafts; maybe expose the presence of Rock Crystals in a chunk?  Astral tries to prevent drops if a player doesn't mine the ore, so we could act as a scout
- [ ] Linking Tool - Need to test if it already works in a Turtle
- [x] Resplendent Prism - Enchantment bonus properties
- [ ] Altars - Valid structure, starlight level, valid recipe
- [ ] Attunement Altar - Active constellation
- [x] Spectral Relay - Check functionality, as these are multipurpose...
- [x] Lightwell - ~~Maybe allow inserting items?  Normally forces a right-click to do so...~~ Not dealing with Hellfire's anti-fake-player stuff
- [x] Ritual Pedestal - Active ritual and the ritual's strength
- [x] Celestial Gateway - List available destinations

Research required \(AKA Nerdpie hasn't used this feature yet\):
- [ ] Irradiant Star
- [x] Wands
- [ ] Gems \(astralsorcery:itemperkgem\)
- [ ] Sealing Sigil
- [x] Mantle of Stars
- [ ] Neromantic Prime, Fysallidic Prime
- [ ] Evershifting Fountain

Not adding:
- Scroll of Written Expertise - I don't see any need to expose its contents, honestly.
- Sextants - Used for verifying multiblocks and finding worldgen features, such as Astral temples, villages, and even specific biomes; multiblocks can be verified using structure definitions (e.g. tell a Turtle how the blocks are laid out), and the worldgen component would amount to "here's the coordinates", which feels severely unbalanced and breaks immersion.

**Comment by Nerdpie** [comment]
There are additional items and blocks that I may want to add support for, but I will have to check that over later.  At present, one of my concerns is balance; I want to expose useful data to the player, such as the stats on their crystals, but I do not want to disrupt Astral's design.  For instance, I believe that the crystal stats are hidden at first, with the tooltip saying that "there is something here, but you do not know what to make of it" or something similar; the same goes for the attuned constellations.  At first, I was thinking about using the computer's owner (I forget if that applies to computers or just turtles...), or possibly a bound Introspection Module, but the Scroll of Written Expertise would also work as a means of controlling what to show, assuming that it can be passed into the context for a `getItemMeta` call.

Another possibility is integration-specific configs, such that, should we implement a gated metadata visibility by, say, passing an Introspection Module to a method, a player/pack could enable a setting that amounts to 'forget the balance, I want the easy code', causing the metadata to show without requiring the corresponding progress in Astral.

Regardless, trying to stay in line with Astral's balance is likely to be a colossal mess...

**Comment by SquidDev** [comment]
>  For instance, I believe that the crystal stats are hidden at first, with the tooltip saying that "there is something here, but you do not know what to make of it" or something similar; [...] but the Scroll of Written Expertise would also work as a means of controlling what to show, assuming that it can be passed into the context for a `getItemMeta` call.

This is something I thought about a lot when considering Thaumcraft integration. It's a similar situation - you only want to expose some information when you've got googles of revealing, and gate other knowledge of research progress. 

I never really found a good solution to this, but might be worth typing up my notes:

Basically the "best" thing to do would be to expose the scroll of written expertise as a module - this can then inject additional information into the context which meta providers can be queried.

The issue, like you say, is how you actually get that into the context of a `getItemMeta` call. One possible idea would be to use any modules on the entire wired network (so any manipulators connected to modems, etc...)<sup>1</sup> - so if you've got goggles of revealing _anywhere_ then they'll be available.

However, a couple of issues with this:
 - I don't know if this is intuitive to the user. It's definitely makes sense to me, as it fits into how modules just "enable" features, rather than explicitly adding them, but may just seem like magic to others.
 - Neither CC:T's network API nor Plethora's context system really support any of the features required for this right now, so would probably need to be rethought a little (though that is the case anyway TBH).

<sup>1</sup> If you're not on a wired network, this'd just be manipulators/modules on the 6 adjacent sides of a computer.

**Comment by Nerdpie** [comment]
Well, some of the pieces I can pretty easily gate; for instance, there's three tiers of telescopes.  I can gate what data they reveal based on what is needed to get to that tier.

Hmmm... I'm not sure if it'd be any cleaner, but, at least on items, we could potentially have some sort of item analyzer block, which acts as a manipulator of sorts.  Depending on the item(s) socketed into it, we could add an extra bit of NBT to items (... I really dislike NBT bloat, though.  Always afraid of tags getting too large, especially with things like bags or Akashic Tome...) that would basically say "expose this type of metadata".  We could also add a config setting (possibly per-integration?) for revealing all of the data regardless.  (Side note: how problematic would it be to add a config for existing features, such as whether to hide the 'secret' Forestry mutations?)

If we would go the route of 'available modules on a network', two pieces come to mind:
- How would we determine which module to use, if multiple are on the network?  For example, if players are doing co-op, and we use Introspection Modules to expose a player's Astral knowledge, how would we determine which player's knowledge to use?  We could define comparisons (who has progressed further?) or aggregators (player A knows constellations 1, 2, and 3, while player B knows 4, 5, and 6, so we expose all six) for such cases, but again, complexity.
- Regarding discoverability and how intuitive a feature is, we could always have some manner of placeholder.  For instance, if a player calls `getItemMeta` on a Rock Crystal, return something to the effect of `"astral":"Cannot detect Astral Sorcery properties without a Scroll of Written Expertise or bound Introspection Module in the network."` in place of the actual metadata.

**Comment by Nerdpie** [comment]
Some of the features that I suggested above may not be possible without a modem that functions similarly to Actually Additions' Phantomfaces or Thaumic Tinkerer's Transvector Interface, as multiblocks have issues with blocks that return `true` for the Forge `isAir` check...

**Comment by Nerdpie** [comment]
For cross-reference, see PR #205 .

**Comment by SquidDev** [comment]
@Nerdpie Is there anything else you'd like to do here, or can this be closed for now?

**Comment by Nerdpie** [comment]
For the time being, I'm going to say that this can be closed.
