### ISSUE TITLE
capture not working after world reload

### ISSUE THREAD

**Issue by JJSax** [SquidDev-CC/ccjam-2016#193]
When I reload my world capture no longer works and errors out when launching my program.

I'm using a regular computer and it works fine once I unbind the chat module, then rebind it.  But I have to do that every time I relaunch the game.

I'm am playing in enigmatica 2 expert btw if you need to know.

**Comment by SquidDev** [comment]
I suspect this was fixed along with the changes made in #167. Could you try [this build](https://www.dropbox.com/s/de5e1ghj80qm7he/plethora-1.12.2-1.1.13-world-npe.jar?dl=1) and see if it makes any difference?

**Comment by JJSax** [comment]
I did use the link you provided and it seems to be working now.  The number on the file name is the same version I had, but I assumed it just needed to be renamed.  That does fix it though.  Good work!

**Comment by JJSax** [comment]
Now that I've played a bit more, I'm finding that at times with the build you linked, the tell method seems to stop working on occasions.  I'll do some testing and see what patterns I can find.

**Comment by SquidDev** [comment]
Hopefully this'll have been fixed in 1.2.0 - Chat recorders got a little bit of a rework. Do tell me if the issue continues to occur.
