### ISSUE TITLE
GitHub Issue Templates

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#195]
Although Plethora doesn't have too many issues in the tracker, it may be beneficial to set up issue templates.  These [templates](https://github.com/CyclopsMC/CommonCapabilities/tree/master-1.12/.github/ISSUE_TEMPLATE) from CyclopsMC's CommonCapabilities may be a good starting point.

Plethora might benefit from a template specifically for mod support.  I don't know off hand how difficult it would be, but we could configure the `Mod integration` project to automatically track issues made with such a template, as well as reminding users to check said project first.

I will gladly draft templates and open a PR, but I would like feedback on:
- How useful would templates be for Plethora?
- What templates would we want?
- Do we want any particular details in the templates, such as thanking users for their interest, or requesting that logs be included via Pastebin/Gist/etc. ?

**Comment by SquidDev** [comment]
Just as a bit of reference, [this](https://github.com/SquidDev-CC/CC-Tweaked/tree/master/.github/ISSUE_TEMPLATE) is what I currently use for CC: Tweaked. Worth mentioning there's some comments there, so make sure to view the raw source.

We could probably do something similar for Plethora. It might be good to make them friendlier, though also want to avoid adding too many words as it may be overwhelming...

It may also be good to have a specific "mod integration" issue, asking people to give detailed use-cases, maybe code samples in some cases, etc... Basically avoiding issues like #160. However, issues like #185 don't really need lots of details, so I'm not too sure.

**Comment by Nerdpie** [comment]
I've copied the templates from CC:T, and made some minor tweaks.  For one, I have the templates automatically applying labels, though that may be open to abuse.  That said, I don't want to create a template for each of the labels that make sense for new issues<sup>1</sup>, as that would be a bit overwhelming for users, and we would want a generic template that isn't tied to a label, just in case.

<sup>1</sup>: It wouldn't make sense for new issues to automatically have labels such as 'duplicate', 'PRs welcome', etc.

**Comment by SquidDev** [comment]
Added in #209. Many 💕 to @Nerdpie for putting those together!
