### ISSUE TITLE
CurseForge Maven

### ISSUE THREAD

**Issue by Nerdpie** [SquidDev-CC/ccjam-2016#199]
I believe that I had mentioned this to @SquidDev on Discord, but I want to revisit the topic.  CurseForge provides a [Maven endpoint](https://authors.curseforge.com/docs/api), which may be beneficial, as several mods also upload deobf and source JARs alongside of releases.  I recall Squid mentioning issues related to a previous attempt to use said endpoint, and want to discuss this before attempting to convert the Gradle dependencies.

On a related note, if anyone know of official Maven repositories for mods that we add support to, please let us know!

**Comment by SquidDev** [comment]
I think I tried it a couple of weeks back, and was unable to get it working for anything but the example file. If anyone has other working instances, I'd be very curious.

**Comment by Nerdpie** [comment]
Well, when searching for an Astral Sorcery Maven repo, all that I found was people pulling from the CurseForge endpoint.  Let me grab an example really quick.  https://github.com/Coders-After-Dark/CompatSkills/blob/master/build.gradle

... figures, I go to find an example of CurseForge for Astral, and I finally find one pointing to an Astral Maven repo... >_<

ETA: Cooking for Blockheads mentions using the CurseForge Maven in its README; could probably pick Blay's brain there, or ask Phylogeny on Direwolf20's Discord.
