### ISSUE TITLE
[REQUEST] Add canvas3d.addItem 

### ISSUE THREAD

**Issue by jakedacatman** [SquidDev-CC/ccjam-2016#200]
Having 3d blocks in the world (with textures) would be better than simulating (kind of) with the block's color as returned by scanner.getBlockMeta.

**Comment by Galaxtone** [comment]
I think it'd be more appropriate to have `box.setTexture()`

**Comment by Lemmmy** [comment]
I think that addItem would be more appropriate - you can't possibly know each item's texture and model ahead of time. OpenPeripherals' overlay glasses allowed you to add blocks, fluids and items, which made creating contextual overlays based on your own logistics systems a breeze. 

Even with something as simple as an ore scanner, you would have to manually maintain a dictionary with ID to texture mappings in every program, which just sounds awful to do. I can certainly see the utility in box.setTexture, but addItem seems more appropriate.
