### ISSUE TITLE
Front face missing for items in frames using canvas3d

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#201]
![Screenshot from 2019-04-14 16-54-32](https://user-images.githubusercontent.com/16342516/56099117-ed5fc680-5ed6-11e9-8c20-717ff8f41195.png)

It seems to pick a random item where it renders correctly. All others are missing a face and the lighting seems off.
```
          b.box = canvas.addFrame({ pos.x, pos.y, pos.z })
          b.box.setDepthTested(false)
          b.box.addItem({ 0, 0 }, b.name, b.damage, 2)
```
Note that there are multiple items being displayed at various depths.

[Test Program](https://github.com/kepler155c/opus-apps/blob/develop-1.8/neural/ores.lua)

**Comment by SquidDev** [comment]
Lem pointed out this is probably due to the depth tested flag not being reset. Should be fairly easy to fix.
