### ISSUE TITLE
[Request] Texture Support

### ISSUE THREAD

**Issue by Galaxtone** [SquidDev-CC/ccjam-2016#202]
The ability to apply textures to a shape with specified areas within the texture

`rectangle.setTexture("minecraft:gui/container/recipe_background.png", 0, 0, 140/256, 78/256)`

`(0,0)` - Top left, `(1,1)` - Bottom right
`(x/width, y/height)` easily refers to a specific pixel position in the image

`box.setTextures({ ["north"] = {"minecraft:location", minX, minY, maxX, maxY}, ["top"] = {...} })`

And the color of the shape could tint the texture. (`0xFFFFFF` -> *All RGB Channels*) (`0xFF0000` -> *Red Channel*)

**Comment by Galaxtone** [comment]
*Replacement for #200 `canvas3d.addItem`*

**Comment by SquidDev** [comment]
Leaking actual texture names is one level of fourth wall I'm not prepared to break. Also, it gets messy when you have to deal with textures which may or may not be part of the atlas, etc...
