### ISSUE TITLE
Turtles do not expose inventory methods

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#204]
Missing list, pushItems, pullItems, etc on turtles when connected directly or via wired modems.

**Comment by SquidDev** [comment]
Fixed in d44ce3c9b38d46f6fe385b417ba51edac51eb00b.

**Comment by HydrantHunter** [comment]
This appears to be an issue again in 1.2.1 (MC 1.12.2).
Tested with CC:T 1.83.1, Plethora 1.2.1, Forge 2768

**Comment by SquidDev** [comment]
@HydrantHunter You need to install Computronics for multi-peripheral support - it's not a bit of Plethora functionality by default.

**Comment by HydrantHunter** [comment]
How did I miss that?  Now I feel dumb.  Thanks for pointing me in the right direction!
