### ISSUE TITLE
Turtle w/introspection module does not show correct transfer locations

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#211]
Turtle with an introspection module is not showing the transfer locations of peripherals connected over a wired network.

![Screenshot from 2019-04-28 18-46-39](https://user-images.githubusercontent.com/16342516/56871023-26735d00-69e6-11e9-934c-bc3fefacb1a7.png)

Calling getInventory().getTransferLocations() only shows "bottom" and "right". Note that you can still transfer to these peripherals.

**Comment by SquidDev** [comment]
OK, so technically this is "working as intended". The introspection module is on a different wired network to the chests, and so you wouldn't expect to be able to transfer them - you'd see the same if the introspection module was replaced by a chest.

However, this is rather unideal behaviour, and pretty unintuitive. That said, I'm not really sure how best to fix it - you'd need to keep track of which networks a turtle is attached to and somehow relay that to turtle upgrades.

**Comment by kepler155c** [comment]
Agreed on "working as intended"
