### ISSUE TITLE
SwitchCraft bug-fest

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#22]
- [x] Dupe bug with firing lasers 
 - [x] Peripherals are not being re-bound
 - [x] Neural interface discards items when closing/labeling/creative mode (see #12)
 - [x] Item transferring doesn't work with non-`IItemHandler` inventories.
 - [x] Activate TNT with lasers
 - ~~Staff invisible players (and invisibility potions) are detectable by entity sensors (spectator works fine though)~~ - Not going to fix
 - [x] Neural Interface does not attach to (or render on) Horse, Shulker, Polar Bear
 - [x] Can't open neural interfaces with disk drives (maybe intended?)
 - ~~Endermen are invisible after teleportation.~~ - Not actually the issue, not sure how to solve the root cause.
 - [x] laserDrill.lua example seems to shoot laser in a willy nilly direction
 - ~~Transferring items while true causes extreme lag (almost server halting)~~
 - [x] Elytra + Kinetic Augment is incredibly overpowered (....try it yourself in game.......no this is not okay....unless it consumes actual fuel.....)
 - ~~Dupe bugs with rapid transfer of items~~
 - [x] Putting 2 stacked modules (laser for example) into the Neural Connector, then removing one of them yields "The module has been removed". It is only possible to put 2 in with Creative mode.
 - [x] Text content is not set for printed pages.
 - [x] Given large velocity when launching via kinetic augment and wearing elytra.
 - [x] `fire.lua` has an incorrect `deltaAngle`.
 - [x] Manipulator MK I and II have a duplicate description 
 - [x] Potions should display the effect ID?
 - [x] In singleplayer, Shift+Using a block with an introspection module, and then hovering over the module in the inventory causes this crash: http://pastebin.com/14NVzgjF

**Comment by Lemmmy** [comment]
- Item transferring does not work with Iron chests

**Comment by inklit** [comment]
- Ratelimit launch function

**Comment by demhydraz** [comment]
This must be the most bug reports you've ever gotten.

**Comment by demhydraz** [comment]
- [ ] Firing lasers from manipulators does not work (no particle, no effects.)

**Comment by SquidDev** [comment]
>  Firing lasers from manipulators does not work (no particle, no effects.)

I believe this is a Sponge/GriefProtection issue though you'd have to check with @inklit.

**Comment by Lemmmy** [comment]
- Staff invisible players (and invisibility potions) are detectable by entity sensors (spectator works fine though)

**Comment by inklit** [comment]
- Neural Interface does not attach to Horse
- Neural Interface does not attach to Shulker
- Neural Interface does not attach to Polar Bear
- ~~Neural Interface does not attach to Trap Skeleton (Normal skeleton with Iron Helmet)~~

**Comment by demhydraz** [comment]
- [ ] Can't open neural interfaces with disk drives (maybe intended?)

**Comment by demhydraz** [comment]
> - Neural Interface does not attach to Trap Skeleton (Normal skeleton with Iron Helmet)

Intended. The Neural Interface goes in the helmet slot.

**Comment by demhydraz** [comment]
- [ ] Endermen are invisible after teleportation

**Comment by inklit** [comment]
- Putting 2 stacked modules (laser for example) into the Neural Connector, then removing one of them yields "The module has been removed". It is only possible to put 2 in with Creative mode.
- Items in the Neural Connector disappear when in Creative mode.

**Comment by inklit** [comment]
- laserDrill.lua example seems to shoot laser in a willy nilly direction

**Comment by inklit** [comment]
- Theoretical fix for item transfer over network through claims: Check isBlockProtected first. This will break on SwitchCraft since isBlockProtected will always return true inside of a claim, though. Until Sponge's onBlockPre event cause is fixed, this shouldn't be implemented. (But it should work once Sponge fixes https://github.com/SpongePowered/SpongeCommon/issues/1022)

**Comment by Lemmmy** [comment]
- Transferring items while true causes extreme lag (almost server halting)

**Comment by inklit** [comment]
- Elytra + Kinetic Augment is incredibly overpowered (....try it yourself in game.......no this is not okay....unless it consumes actual fuel.....)

**Comment by Lemmmy** [comment]
- **DUPE** Rapidly transferring items between a furnace and a chest, then right clicking it (while its rapidly moving) to half the stack duplicates the stack.

```
local a = peripheral.find("Chest")
local b = peripheral.find("Furnace")

while true do
    a.pushItems("Furnace_0", 1)
    a.pullItems("Furnace_0", 1)
end
```

**Comment by demhydraz** [comment]
- **DUPE** Rapidly transferring items between two slots in a chest, then pulling out one of the stacks will duplicate the stack.
```lua
local a = peripheral.wrap('Chest_N') -- where N is a number

while true do
  a.pullItems('Chest_N', 1, 64, 2) -- Same number as above
  a.pullItems('Chest_N', 2, 64, 1)
end
```

**Comment by SquidDev** [comment]
> Staff invisible players (and invisibility potions) are detectable by entity sensors (spectator works fine though)

I'm in two minds about this. The sensor doesn't really have any "lore" at the moment, but if it uses ultrasound or something then it would make sense for it to still "see" invisible players. I don't think I can't do anything about players sponge has made invisible as the server doesn't know any different.

> Neural Interface does not attach to Horse, etc..

I think it _may_ attach to them, just not render as I haven't added hooks for it. I will double check though. I'm not sure what to do though as the overlay looks kinda stupid on them. Maybe a custom monocle model.

> laserDrill.lua example seems to shoot laser in a willy nilly direction

Yeah, it converts from radians to degrees when it shouldn't. I changed the output of a function and forgot to update the example.

> Transferring items while true causes extreme lag (almost server halting)

We've seen this with `turtle.suck` as well, I'm beginning to wonder whether this is a Sponge bug. I will see what I can do though. Something @inklit can do on the server side is add a "base cost" to the `pushItems` and `pullItems` methods in order to limit it.

> Elytra + Kinetic Augment is incredibly overpowered (....try it yourself in game.......no this is not okay....unless it consumes actual fuel.....)

That is something really awesome that I hadn't even thought about. Yeah, there needs to be some rate limiting on lasers/kinetic augments in item form. Also scaling down the y axis.

**Comment by demhydraz** [comment]
Still no TNT lasering? :<

**Comment by SquidDev** [comment]
I want to get bug fixes in first, but also this shouldn't be too hard.

**Comment by demhydraz** [comment]
That's the most important bug fix! :stuck_out_tongue:

**Comment by inklit** [comment]
Haha as important as TNT lasering is, I think there is more important bugs.

**Comment by inklit** [comment]
- TNT ignited by a laser is invisible until it explodes
-  fire.lua example only shoots in 1 direction

**Comment by Lignum** [comment]
- Manipulator MK I and II have a duplicate description ![](https://shitty.download/n1gRWq.png)

**Comment by SquidDev** [comment]
- Text content is not set for printed pages.
- Given large velocity when launching via kinetic augment and wearing elytra.
- `fire.lua` has an incorrect `deltaAngle`.

**Comment by Lemmmy** [comment]
Potions should display the effect ID?

**Comment by Lignum** [comment]
- In singleplayer (probably also multiplayer), Shift+Useing a block (and air? haven't tried) with an introspection module, and then hovering over the module in the inventory causes this crash: http://pastebin.com/14NVzgjF

**Comment by SquidDev** [comment]
> - **DUPE** Rapidly transferring items between a furnace and a chest, then right clicking it (while its rapidly moving) to half the stack duplicates the stack.
> - **DUPE** Rapidly transferring items between two slots in a chest, then pulling out one of the stacks will duplicate the stack.
 
[Probably relevant](https://github.com/SpongePowered/SpongeForge/issues/965#issuecomment-261603239) seeing as this only occurs on Sponge servers.

> - Dupe bug with firing lasers

Only occurs with GriefPrevention installed: it appears blocks are reset and then broken again.

**Comment by SquidDev** [comment]
The latest commit enables Sponge to correctly associate the laser with the manipulator, fixing the dupe bug. I've also posted a question on the GriefPrevention tracker to see if there is a better way of handling this: MinecraftPortCentral/GriefPrevention#214.

There is nothing I can do about item dupe bugs: I'll have a dig through Sponge and see if it is trivially fixable.
