### ISSUE TITLE
[1.12.2 - 1.2.1] Shutdown commands reboot the Neural Connector instead of turning it off

### ISSUE THREAD

**Issue by HydrantHunter** [SquidDev-CC/ccjam-2016#222]
MC 1.12.2
CC:T 1.83.1
Plethora 1.2.1

What's happening:  When using control-S, 'shutdown' from the command line, or os.shutdown in Lua, the neural connector restarts instead of turning off.

What's expected:  When using one of the aforementioned actions the neural connector will turn off and stay off.

Thanks for Plethora, and all your work on CC in general!

**Comment by SquidDev** [comment]
Hrmr. So this is _technically_ working as intended, except it obviously isn't. Neural interfaces turn on automatically when in the player's helmet slot, and so when you shut it down they'll just turn-on immediately.

I guess the "cleanest" thing to do here would be to only turn on the computer when the slot it is in changes.

**Comment by HydrantHunter** [comment]
An interesting conundrum - I wondered if the relationship between the Neural Interface and the Connector might be part of why it behaved that way.

FWIW, your suggested solution sounds fine to me.
