### ISSUE TITLE
Allow for wired modems to be attached to manipulators

### ISSUE THREAD

**Issue by golyalpha** [SquidDev-CC/ccjam-2016#225]
It'd be great if we could attach wired modems directly to manipulators and use them to connect them to the computers, just like with could with OpenPeripheral peripherals (like sensors for example). 

Not sure if it's because I'm running CC:Tweaked instead of ComputerCraft, but I would've thought that this part of the mod would be the same between the two.

**Comment by SquidDev** [comment]
You should be able to use the full block modems (crafted from just a wired modem) to connect to manipulators.

I may be misunderstanding you though. If so could you post a screenshot of what you're trying to do?

**Comment by golyalpha** [comment]
I was trying to use the classic modems as provided by ComputerCraft, which if you're only trying to interface with that one block is a more appropriate choice, I believe.
