### ISSUE TITLE
Question: Disabling Chat Recorder

### ISSUE THREAD

**Issue by KingCol13** [SquidDev-CC/ccjam-2016#231]
On the server I play on, chat recorders are able to read private messages between players, even without binding the chat recorder. I suspect this is more a problem with how that plugin works than anything else. I've tried for a few hours to blacklist the chat recorder module in plethora-core.cfg but I haven't been able to. This is what I expected to work:

> \# List of modules to blacklist.
>     S:blacklistModules < plethora:chat
>      >

Could you tell me what I'm doing wrong?
Otherwise would there be a way to blacklist just the chat_message event?

Versions:
FTB Ultimate Reloaded 1.9.0
cc-tweaked-1.12.2-1.84.0
plethora-1.12.2-1.2.2

p.s: sorry to bother you with this and thanks for the great mods! I love them!

**Comment by SquidDev** [comment]
Hrm, that's very odd - chat recorders definitely shouldn't be doing anything if they're blacklisted. I'll have a look to see what's going on - should hopefully be quite simple to fix.

Relatedly, do you know what chat plugin you're using? I'll see if there's anything I can do on my end to avoid this.

**Comment by KingCol13** [comment]
I think I'm not managing to blacklist them properly because it generated a .errored file and replaces my edited config file with the default.

The chat plugin is UltimateChat. The server also uses DiscordSRV to connect to the discord chat, which doesn't show PMs. I checked with Peripherals Plus One and Computronics chat boxes and they both have this same problem, so I doubt it's your end.

Thanks for your reply :)

**Comment by SquidDev** [comment]
You can try using Forge's config GUI to edit the Plethora Core config file on the client, and then copy the relevant sections to the server. It might be that the string requires quotes or something - the format is a little odd.

**Comment by KingCol13** [comment]
Ah that work's, brilliant. I didn't even know about the editor in the client thanks! Apparently I was missing a newline and an indent.

Thanks for all your help. I'll close it here but if there's anything else you want to know get in touch.

**Comment by SquidDev** [comment]
Fantastic, glad you've got it working :).
