### ISSUE TITLE
Astral Sorcery bag

### ISSUE THREAD

**Issue by Lazersgm** [SquidDev-CC/ccjam-2016#232]
a bag to hold rock crystals in. since each one takes a bag slot i just gathered some and now the rest go in the trash can. would be nice to have a bag that can only hold them and has say 100 slots?

**Comment by SquidDev** [comment]
Plethora is really meant to be about adding peripherals and functionality to ComputerCraft, and tries not to add new features directly related to other mods. I'd suggest filing this on Astral Sourcery's GH instead.
