### ISSUE TITLE
Can't find way to pull/push items across network.

### ISSUE THREAD

**Issue by mmance** [SquidDev-CC/ccjam-2016#235]
I have been able to use pullitem and pushitem to move between adjacent inventories, but I can't figure out how to move to another inventory on the network.

I have cc-tweaked installed.  I looked at the documentation, both in game and on the wiki, but there are no examples for remote inventories.  I do not see remote inventories when I try getTransferLocations().

Thank you for a wonderful mod.

**Comment by SquidDev** [comment]
Hrmr, can you post a screenshot of your wired network?

**Comment by mmance** [comment]
![](https://www.mmance.com/sites/default/files/netsetup.png)

I think I figured it out.  I am trying to move from the small chest to the big chest, but the small chest is only  a peripheral on the computer, it does not have a modem.  When I looked at getTransferLocations() on the bigchest, I could see everything except the small chest.

Guess everything has to have a modem and not just be a peripheral directly.

Thank you so much for getting back to me quickly.  I posted the picture of the setup as to maybe help someone else with this issue.

**Comment by mmance** [comment]
![](https://www.mmance.com/sites/default/files/netsetup2.png)

I also wanted to point out that even though I added a wired modem block to the small chest, it does not work yet, because my code says peripheral.find('chest') it wraps as "top" instead of via the modem.

**Comment by SquidDev** [comment]
I think all your questions are answered, so closing this. Just shout if I missed something, and I'll reopen.
