### ISSUE TITLE
all key detection on neural interface

### ISSUE THREAD

**Issue by Magicmaan** [SquidDev-CC/ccjam-2016#240]
not sure if it's just a bug, not implemented or i'm just plain stupid but i cant seem to pull the key event and it detect when outside the terminal interface.
I did notice you using it though in your examples on the website so i'm not too sure

**Comment by SquidDev** [comment]
You need to add a keyboard in a module slot on your interface. The docs [explain it a little bit](https://squiddev-cc.github.io/plethora/items/keyboard.html#using-with-the-neural-interface), but the examples should probably clarify that too.

**Comment by Magicmaan** [comment]
> 
> 
> You need to add a keyboard in a module slot on your interface. The docs [explain it a little bit](https://squiddev-cc.github.io/plethora/items/keyboard.html#using-with-the-neural-interface), but the examples should probably clarify that too.

ahh thanks, have been confused for a while now but makes sense
