### ISSUE TITLE
Null Pointer when calling getMetadata on Immersive Engineering Item

### ISSUE THREAD

**Issue by fionera** [SquidDev-CC/ccjam-2016#250]
## Useful information to include:
MC 1.12.2
CC:T 1.84.0
Plethora 1.2.3

## Reproduce
Call `getMetadata()` on a ItemStack from AE2 with the Data from this Image: https://media.discordapp.net/attachments/477911902152949771/671036714734714891/unknown.png

## Log files
https://pastebin.com/RjnaXJw4

**Comment by SquidDev** [comment]
This is a bug in Immersive Engineering. It appears to have been reported and fixed a few months ago in 0.12-92 (see BluSunrize/ImmersiveEngineering#3560). Are you sure you're running the latest version?

**Comment by fionera** [comment]
Ah ok I didnt check that sorry... The pack is running 0.12-91
