### ISSUE TITLE
Peripherals Plus One support

### ISSUE THREAD

**Issue by Dalethium** [SquidDev-CC/ccjam-2016#255]
https://www.curseforge.com/minecraft/mc-mods/peripheralsplusone

Should just include support for peripherals from this mod such as it's speaker.

Please note that the library this mod depends on has a crash in it depending on the mods used, here is the issue I created regarding it: https://github.com/austinv11/CollectiveFramework/issues/8

and here is my personally fixed build: https://github.com/WeNeedCoffee/TheFramework/releases/tag/v1.12.2-1.0.1-COFFEEFIX

**Comment by SquidDev** [comment]
I'm afraid I'm not going to add Peripherals+=1 support, as at this point it's fairly unmaintained and doesn't really have an API which makes adding support easy.
