### ISSUE TITLE
Scanner module on turtle returns incorrect block coordinates.

### ISSUE THREAD

**Issue by DanTechMust** [SquidDev-CC/ccjam-2016#265]
**Minecraft version: 1.12.2
CC: Tweaked version: cc-tweaked-1.12.2-1.84.0
Plethora version: plethora-1.12.2-1.2.3**

Detailed reproduction steps: 
1. Place turtle with facing on **+X or -X or Z+ but not Z- coordinate**
2. Use .scan()
3. Move to location turtle relative

**If place with Z- facing the .scan() returns correct turtle relative coordinates of blocks.**

**Expected result A:** .scan() method use turtle Transform matrix include rotation of turtle to return block coordinates.
**Expected result B:** .scan() must use turtle facing to calculate right positions of blocks.

Thx for that mod :)

**Comment by SquidDev** [comment]
Hmmr, I don't really think this is a bug, just an unfortunate collapse of the fourth wall. 

Translating things between coordinate systems ends up being terribly messy[^1] and honestly not what you want a lot of the time. 

[^1]: You end up having to translate everything, including pitch/yaw of entities, entity positions, etc...

**Comment by DanTechMust** [comment]
I have created complex rotation system turtle works perfectly in local coordinate system, rotation, moving etc.
But .scan() returns (WorldBlockCoordinate - TurtlePosition - scanradius / 2 +- 1) thats no actual transformation to local space.

While turtle can't work in global coordinates I need to use local coordinate system only, so I think .scan() not doing their job fully.
Did you talk about "optimisations" in this case "Translating things between coordinate systems ends up being terribly messy"? But this translations happens every frame in any game.
Let me ask you, is that function .scan() easy to use for anybody, including that they need to implement their own transformation to work with?
So function works but sensor module lose half of their meaning.

**Comment by DanTechMust** [comment]
local directions = 
{
    {x = {x = 1, y = 0}, y = {x = 0, y = 1}, f = function(x, y) return x, y end},
    {x = {x = 1, y = 0}, y = {x = 0, y = -1},f = function(x, y) return x, -y end},
    {x = {x = -1, y = 0},y = {x = 0, y = 1}, f = function(x, y) return -x, y end},
    {x = {x = -1, y = 0},y = {x = 0, y = -1},f = function(x, y) return -x, -y end},
    {x = {x = 0, y = 1}, y = {x = 1, y = 0}, f = function(x, y) return y, x end},
    {x = {x = 0, y = 1}, y = {x = -1, y = 0},f = function(x, y) return y, -x end},
    {x = {x = 0, y = -1},y = {x = 1, y = 0}, f = function(x, y) return -y, x end},
    {x = {x = 0, y = -1},y = {x = -1, y = 0},f = function(x, y) return -y, -x end},
}


That what I use for calibration.....
Man you must add WorldToLocal or something inside MethodsScanner .scan() method.
