### ISSUE TITLE
2 new methods for Forge Energy producing/consuming blocks.

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/ccjam-2016#266]
I have a few energy storage monitor programs that, when attempting to get how much energy is currently being used, will average the `energyCell.getRFLevel()` across 10 scans.  This works well and good, but with that being said, you can't get accurate numbers for how much is being used and generated at once.  I'd like to be able to state, "We are using 500 RF/t and generating 600 RF/t, that's why we are increasing at 100 RF/t", but currently I can only state, "We are increasing at 100 RF/t".

I propose the two functions, 
1. `getRFUsedLastTick`
2. `getRFGainedLastTick`

Where Gained + Used = the actual difference between the tick before and the tick the info is grabbed on (the "increasing at 100 RF/t" part).

**Comment by SquidDev** [comment]
The Forge API doesn't allow you to track energy usage, so I'm afraid this isn't really feasible.
