### ISSUE TITLE
Inventory methods not available when a turtle  wraps another turtle

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/ccjam-2016#267]
## Useful information to include:
 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.87.0
 - Plethora version: 1.2.3
 - Mod pack link: https://www.curseforge.com/minecraft/modpacks/a-thinking-pack-2
 - Mod pack version: 1.0.4
 - Detailed reproduction steps: Stack two advanced crafting turtles (as pulled from the creative menu). My turtles had the same ID. In the lua program on the top turtle, wrap the lower turtle. Note that the plethora inventory methods are missing but the computer ones are present.

**Comment by SquidDev** [comment]
This is working as expected. Plethora's peripheral provider has the lowest priority, and so other providers (such as that for computers/turtles) takes priority.

[Computronics](https://github.com/Vexatos/Computronics) provides "multi-peripheral" support, which means that a turtle will expose both the computer and Plethora peripherals in one go. This is probably what you want.

**Comment by Wojbie** [comment]
Issues from this issue might be tangentially related to what SquidDev-CC/CC-Tweaked#452 aims to solve.

**Comment by SquidDev** [comment]
Oh, I'm not even sure if I want to deal with multi-peripherals as part of that. It's a messy issue - you can do something simple for sure, but there's a whole bunch of discussion in dan200/ComputerCraft#153 about some of the complexities.

**Comment by Wojbie** [comment]
Oh no i was referencing that specifically inventory methods would became available if ideas from that issue for implemented. Multi-peripherals are big and complicated issue.
