### ISSUE TITLE
Advanced Introspection Module

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/ccjam-2016#268]
## Useful information to include:
 - Explanation of how the feature/change should work.

The "Advanced Introspection Module" will give the same functionality as the "Introspection Module", BUT instead of needing to have it connected locally, you can control chests remotely

 - Some rationale/use case for a feature. Everything takes time to implement, so I like to have a solid justification for each feature.

Example: Lets say you have a storage system, and you need to transfer some kind of item, but you can't, because there is no way to transfer an item remotely.

**Comment by SquidDev** [comment]
I really don't want to have remote interaction with peripherals. It's hard to correctly, and I don't think makes sense from a gameplay/thematic point of view.

It's possible to do remote inventory transfer by going via a player's ender chest (or their normal inventory).
