### ISSUE TITLE
Creeper explosions of any kind do not drop Neural Interface

### ISSUE THREAD

**Issue by snightshade** [SquidDev-CC/ccjam-2016#27]
If a creeper with a Neural Interface and Kinetic Augment attached explodes by any means, the Neural Interface will not drop as an item.

**Comment by SquidDev** [comment]
This will be tricky to fix as creepers exploding simply set the dead flag to true and so I cannot add hooks to drop items. It might be possible to hook into `ExplosionEvent.Start` to drop the item then. Though that is kinda ugly.

**Comment by SquidDev** [comment]
Right, I've decided that I'm not going to fix this. It kinda makes sense that an explosion would destroy this delicate piece of equipment.
