### ISSUE TITLE
Player Entity Yaw switches between 3+ different formats randomly

### ISSUE THREAD

**Issue by Trickster29** [SquidDev-CC/ccjam-2016#270]
I made a program that shows what the player is looking at using trig functions with the yaw and pitch of the player using the entity sensor. after teleporting around and moving my program stops working after a bit and i noticed that the yaw wasn't using 0-359 anymore
it was using -180 to 180 
then after a while it even started using -0 to -359
maybe theres more?

I really think this isn't intended and it probably should stick to 1 format so that code is consistent

 - Minecraft version 1.12.2
 - CC: Tweaked version cc-tweaked-1.12.2-1.88.0
 - Plethora version plethora-1.12.2-1.2.3
 - Detailed reproduction steps:
 
1. maybe reboot neural implant pc multiple times
2. maybe circle your head and move 
3. maybe teleport around
3. eventually yaw will change formats

**Comment by SquidDev** [comment]
This is probably Minecraft just being inconsistent with angles. I should probably normalise them on my end, but doing `yaw % 360` should work as a Lua-side bodge.

**Comment by Trickster29** [comment]
i have a video now on exactly how to reproduce if you'd like i just gotta upload it

**Comment by Trickster29** [comment]
https://youtu.be/4Oc0YmjHrR0

Edit:
Btw looks like the botch fix fixed it, for now, thanks!
