### ISSUE TITLE
Laser lighting nether portal

### ISSUE THREAD

**Issue by exerro** [SquidDev-CC/ccjam-2016#28]
It'd be really useful if the laser lit nether portals, particularly as a handheld item.

**Comment by SquidDev** [comment]
Nether portals are lit by creating a fire near the nether portal frame: be it from burning blocks or a flint and steel. I'm not sure whether I want lasers to light fires where they hit or not. It makes sense, and we already do it for entities, however it doesn't seem ideal behaviour most of the time.

**Comment by inklit** [comment]
I don't think that they should light fires either.

**Comment by exerro** [comment]
I think for general blocks it doesn't work, but obsidian is supposed to be extra-tough, so making just them light on fire (as opposed to disintegrating, like less tough substances do irl) would make sense to me. It's so convenient being able to use the laser - an already useful item - to do another task, rather than having to carry around a flint and steel.
