### ISSUE TITLE
Cannot right click a pig with a saddle with Neural Connector

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/ccjam-2016#29]
You cannot right click a pig with a saddle with Neural Connector to get into the Neural Connector menu.
It attempts to mount the pig instead, perhaps shift+click or left click (would damage the pig, but at least you can program it) would be a good way to get around this.

**Comment by inklit** [comment]
Thanks!

**Comment by SquidDev** [comment]
No problem. Worth noting that this has client side changes so you can't just bump the server version. I'm hoping to get a release out soonish so it might be worth waiting for that.

**Comment by SquidDev** [comment]
This fix does not correctly handle interacting with entities. Reopening.

**Comment by SquidDev** [comment]
Reopening as it is broken in 1.10.
