### ISSUE TITLE
Chat module

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#30]
Adds the ability to intercept chat events & stop them. This would be useful for programming custom commands (`!give minecraft:dirt` could fetch dirt from a chest).

I'm not sure about this: there are always chat boxes from various mods.

**Comment by inklit** [comment]
Not sure if this is mod is a good fit for this system.
I dont think the ability to stop chat events is a good idea. It would inevitable end up being abused.
If you do end up doing it, you should do something similar what MinimalPeripherals does and cancel chat events that start with \ and forward those messages to your chat module. Using the same method may have interference though.

**Comment by SquidDev** [comment]
> Not sure if this is mod is a good fit for this system.

Yeah, I'm not 100% sure about this. It would be immensely useful, I just don't know if I should leave it for other peripheral mods.

> I dont think the ability to stop chat events is a good idea.

This was always going to be just for the current player's chat events so should be less abusable. I'm not sure yet whether it would just capture messages starting with `!`, or allow specifying a custom pattern instead.

It might just be better to leave it and use #9 to implement the same behaviour (right click keyboard and type what you want). Though then there is no visual feedback on what you are typing.

**Comment by exerro** [comment]
I like the idea. If you could stop any message, you could potentially write chat filters (filtering certain words, for example). Of course, this could be abused if left open to any player, so being able to disable it or limit it to command computers would help.

> Not a good fit for the system

On the contrary, Plethora seems to be about providing interfaces to native (and modded) minecraft through computers. Maybe a chat-box-like peripheral or module would be a good way to go, for consistency?

If you only use one symbol for the beginning character, please use a different symbol though. `!` is a pain to type. Something near `t` or `/` physically would be better in my opinion.

**Comment by inklit** [comment]
I misinterpreted his original idea for this. The way I interpret it now, @Exerro, is that this is some sort of module you install on your Neural Connector that only affects you.

Cancelling of the event would only apply to messages going to you, or messages from you.
The filter for whether or not to cancel an event should probably just be programmatic and not explicitly defined.
If this is the case, then I think this would be fine to implement.

**Comment by SquidDev** [comment]
Right, I'm probably going to go for these methods for now:

 - `say(message:string)`: says a message "as" the wearing player. Broadcasts to the whole world.
 - `tell(message:string)`: says a message to the wearing player.
 - `capture(pattern:string)`: matches chat events against a pattern, discarding those which match.
 - `removeCapture(pattern:string)`: remove a particular capture.

This will also fire events whenever the wearing player says something in chat, irrespective of whether it is "captured" or not.

**Comment by Lignum** [comment]
Would `say` be affected by mutes? Chat boxes are already infuriating enough.

**Comment by inklit** [comment]
@Lignumm Likely not, unless he fires a player chat event to Forge which Sponge can handle. Not sure how well that would work though or if it is even setup in a way to allow for that to work.

**Comment by SquidDev** [comment]
I had a prod through Sponge's code and as long as I fire the correct events, it looks like Sponge will catch it. If not, you can always disable the `say` method.

One thing to consider is how this item could have an in-game use. It doesn't have to have a use, but it would be nice.
