### ISSUE TITLE
Computer minecarts

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#37]
I don't know about this. It is kinda useless, but would be adorable. A couple of things to consider:

 - [x] Right click Minecart with computer (like Quark) to place it inside.
 - [ ] Wraps a manipulator on the back slot.
 - [x] `propel(velocity)` on kinetic augment: Moves the Minecart forwards or backwards along a rail.

**Comment by SquidDev** [comment]
I've added a Minecart computer. Currently there are no items for this: it is just done through "placing" it in an empty minecart. It might be worth considering adding them.

**Comment by JomerDev** [comment]
There was an openComputers minecarts mod that worked well, you might want to take a look at it

**Comment by SquidDev** [comment]
Implemented in #50
