### ISSUE TITLE
Terminal glasses

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/ccjam-2016#39]
It would be really nice to have some form of OpenPeirpheral's terminal glasses. Obviously these will be integrated directly into the neural interface rather than using a terminal bridge. It might be worth looking at [OpenGlasses](http://minecraft.bymarcin.com/OpenGlasses/doku.php?id=start) functions to get an idea of some of the functionality we could add.

---

## Core functionality
 - [x] 2D objects (rectangle, dot, line, triangle, line strip, polygon, text)
   - [ ] Z-index control
 - [x] Object groups. Perhaps we could store the parent ID in each object, and inherit properties from there? We'd need to think about how this interacts with z-indexes.
 - [x] 3D objects (rectangle, dot, line, triangle, cube, polygon, text) It would be good if rectangles, lines and text came in "floating" (facing you) and "normal" varieties.
 - [ ] Render 2D canvas on manipulator.
 - [ ] Optimise network packets: compute diff of changes, compress, etc...

## Other things
 - [x] Block/Fluid/Item rendering
 - [ ] Particles

**Comment by osmarks** [comment]
I'd quite like 3D stuff to be available, even in limited form. It would make a lot of stuff much easier, and ore3d would probably be nicer for servers too.

**Comment by SquidDev** [comment]
All the "interesting" things are in, so I'm going to close this. There's definitely some features here which may get added in the future, but I'd like to discuss them in separate issues when the need arises.
