### ISSUE TITLE
Introspection module item.consume goes into negative

### ISSUE THREAD

**Issue by valithor2** [SquidDev-CC/ccjam-2016#53]
MC: 1.10.2
Plethora 1.1.5
Unborked 1.0.5
CCTweaks 1.3.3
Pam's HarvestCraft 1.9.4-1.10.2g

With an introspection module you can call the consume function on eatable items continuously (only tested on Pam's HarvestCraft food items), and the counter on the items will go into the negatives.  After the counter hits -127 it will loop around to +127 and continue counting down.

**Comment by SquidDev** [comment]
Should be fixed now. Thanks for the report!
