### ISSUE TITLE
[1.10.2] Cannot getBlockMeta on any Thermal Expansion blocks

### ISSUE THREAD

**Issue by mzx987** [SquidDev-CC/ccjam-2016#56]
The title says it all. For some reason, I am currently unable to read metadata from any Thermal Expansion block.
I am currently using Plethora v1.1.5

Here is an in-game screenshot of what I get when attempting to read metadata from all four of them:
http://i.imgur.com/CbSUQ7q.png

Is it something I am doing wrong? Or is there no support for Thermal Expansion?

**Comment by SquidDev** [comment]
This appears to be an issue on their end, just missing a null check. Plethora has a habit of causing this specific problem, as it doesn't come up in most normal gameplay. I've filed a bug report on their end, and will get back to you when I can confirm it is working.

**Comment by SquidDev** [comment]
The issue has been closed on their end, so I presume a release is imminent.
