### ISSUE TITLE
[1.1.6] Plethora Crash

### ISSUE THREAD

**Issue by Alaberti** [SquidDev-CC/ccjam-2016#57]
https://pastebin.com/5WAG3naq

Plethora: 1.1.6
Computercraft: 1.80pr0-2017052315

Pocket Computer compat issue?

**Comment by SquidDev** [comment]
ComputerCraft's internals are very much in flux at the moment, making targeting it rather difficult. I had to change a lot of things for the 1.1.6 release, much of it for naught as things changed a couple of days later. Until there is a stable version of ComputerCraft, I'm not planning to make any more builds targeting the development versions of CC. Sorry.
