### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by vico93** [SquidDev-CC/ccjam-2016#58]
I've got this error trying to launch a server and I'm dumb enough not to know what the problem is:

https://gist.github.com/vpontin/b2b95765da350bff389389a4393a6e26

Minecraft 1.11.2
Forge-1.11.2-13.20.0.2304
CCTweaks-1.11.2-1.4.0
ComputerCraft1.80pr0
plethora-1.11.2-1.1.5
unborked-1.11.2-1.80pr0-1.1.5

**Comment by SquidDev** [comment]
See SquidDev-CC/CCTweaks#159. I didn't actually get round to releasing a 1.11.2 update - I'll do that now.
