### ISSUE TITLE
Cannot transfer items with the latest 1.10.2 release of plethora

### ISSUE THREAD

**Issue by roger109z** [SquidDev-CC/ccjam-2016#59]
Using the latest version of plethora for 1.10.2 I cant transfer items from one chest to another it gives the error "Source for chest "chest" does not exist" but it does exist
![2017-06-25_08 17 20](https://user-images.githubusercontent.com/7905069/27517309-33e32bf6-597f-11e7-9397-210267b7e6fc.png)

**Comment by SquidDev** [comment]
Can I see a picture of your setup? Make sure that both chests are on the same wired network.

**Comment by SquidDev** [comment]
@roger109z Any update on this?

**Comment by roger109z** [comment]
@SquidDev sorry I didn't see you asked me to show my setup they are using a modified cc jar on that server which may be the issue so I don't feel it would be appropriate for me to post an issue here
