### ISSUE TITLE
Draconic evolution reactor support

### ISSUE THREAD

**Issue by kain184** [SquidDev-CC/ccjam-2016#61]
Hello i was wondering if there was a way to get access to the getReactorInfo method that opencomputers can pull from the reactor. i am able to get some other info from the energy gates that draconic evolution provides but not that one. i am trying to make a program that reads the reactor states and cannot seem make it work well without that kind of information.

**Comment by kain184** [comment]
latest version of draconic evolution added support back in for computercraft i will test and see if it allows full access to draconic reactor information and if so i will call this closed.

**Comment by SquidDev** [comment]
Just had a look through DE's code base - it seems that they've added everything which needs adding. If not, I'm happy to add some additional integration.
