### ISSUE TITLE
Plethora crashing serverside in 1.12

### ISSUE THREAD

**Issue by kd8lvt** [SquidDev-CC/ccjam-2016#62]
Crashlog:
[crash-2017-07-27_15.09.27-server.txt](https://github.com/SquidDev-CC/plethora/files/1181028/crash-2017-07-27_15.09.27-server.txt)

If I'm missing something, let me know, I very well could be >.>

**Comment by SquidDev** [comment]
See #60. Sorry about this - I've a couple of other things I want to get into the 1.12 branch before pushing a new release so it may be another couple of days before the fix is released.
