### ISSUE TITLE
Server Crash (MCForge 2443)

### ISSUE THREAD

**Issue by sharkck** [SquidDev-CC/ccjam-2016#63]
The mod does not crash client-side but crashes server-side.

Here is the crash log and server log:

[logs-plethora.zip](https://github.com/SquidDev-CC/plethora/files/1192864/logs-plethora.zip)

[crash-2017-08-02_02.23.21-server-Plethora.txt](https://github.com/SquidDev-CC/plethora/files/1192865/crash-2017-08-02_02.23.21-server-Plethora.txt)

**Comment by SquidDev** [comment]
Ahhh, right. This has been fixed for a while (see #60, #62) I just hadn't got round to releasing it (sorry). It should be [on Curse now](https://minecraft.curseforge.com/projects/plethora-peripherals/files/2459093) though.
