### ISSUE TITLE
Block scanner turtle upgrade

### ISSUE THREAD

**Issue by dunstad** [SquidDev-CC/ccjam-2016#64]
Any chance there could be a turtle upgrade made from the block scanner module somehow? Computercraft seems to be lacking a way to scan terrain from a turtle in all the addons I've looked at so far.

**Comment by SquidDev** [comment]
There should already be support for this - lasers, sensors and scanners are registered as upgrades. Which version are you currently using?

**Comment by dunstad** [comment]
Oh, that's good to hear! I guess I need to improve my github code search skills. I tried looking at the turtles in the creative menu and couldn't see one that seemed likely, but I'm using ComputerCraft-1.80pr0-build10 and plethora-1.10.2-1.1.7-pr0 .

edit: on Minecraft 1.10.2 by the way

**Comment by SquidDev** [comment]
Yeah, they don't show up in the creative or JEI menu. If you've got CCTweaks, then they'll show up when finding the usage of turtles/scanners, but still no physical item. I'll leave this open as a reminder for me to display them :).

**Comment by dunstad** [comment]
Good stuff! I'll try and get one running in a world when I have time now that I know they exist.
