### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by sharkck** [SquidDev-CC/ccjam-2016#65]
Experiencing a crash still with the updated version of Plethora.
Here are the logs:

[crash-2017-08-09_23.29.24-server.txt](https://github.com/SquidDev-CC/plethora/files/1213603/crash-
2017-08-09_23.29.24-server.txt)
[latest.txt](https://github.com/SquidDev-CC/plethora/files/1213600/latest.txt)
[fml-junk-earlystartup.txt](https://github.com/SquidDev-CC/plethora/files/1213602/fml-junk-earlystartup.txt)
[fml-server-latest.txt](https://github.com/SquidDev-CC/plethora/files/1213601/fml-server-latest.txt)

Thought it may be related to Tough As Nails... so I removed that and still got a crash. 
Logs after removing TAN:
[crash-2017-08-09_23.39.30-server.txt](https://github.com/SquidDev-CC/plethora/files/1213607/crash-2017-08-09_23.39.30-server.txt)
[latest.txt](https://github.com/SquidDev-CC/plethora/files/1213606/latest.txt)
[fml-junk-earlystartup.txt](https://github.com/SquidDev-CC/plethora/files/1213608/fml-junk-earlystartup.txt)
[fml-server-latest.txt](https://github.com/SquidDev-CC/plethora/files/1213609/fml-server-latest.txt)

**Comment by sharkck** [comment]
Removed Plethora and looks like the issue is solely with ComputerCraft:

[crash-2017-08-09_23.44.44-server.txt](https://github.com/SquidDev-CC/plethora/files/1213617/crash-2017-08-09_23.44.44-server.txt)
[fml-junk-earlystartup.txt](https://github.com/SquidDev-CC/plethora/files/1213619/fml-junk-earlystartup.txt)
[fml-server-latest.txt](https://github.com/SquidDev-CC/plethora/files/1213618/fml-server-latest.txt)
[latest.txt](https://github.com/SquidDev-CC/plethora/files/1213620/latest.txt)

Also, it appeared possible that Immersive Engineering could be conflicting somehow?  I removed it and got the same crash.

**Comment by sharkck** [comment]
Ok.  I just figured it out.  SOMEHOW a computercraft 1.79 (I think curse auto adds it when I hit 'install' on Plethora') mod file was added to my mods folder.  Removed this and the server starts without issue.

**Comment by SquidDev** [comment]
Hrrmrm, sadly there isn't a lot I can do about this - I really need an official build of ComputerCraft to be released on CurseForge, so I can depend on that.
