### ISSUE TITLE
[1.11.2] Refined storage noclassdef

### ISSUE THREAD

**Issue by Tencao** [SquidDev-CC/ccjam-2016#66]
Calling the function `getMetaOwner()` in Plethora's neural interface with an introspection module yields the following error:
![2017-09-14_15 53 53](https://user-images.githubusercontent.com/8918271/30433568-1a0c64f6-9965-11e7-8301-63943faa3500.png)

**Reproduction:**
**1)** Put a neural interface in your head slot
**2)** Access it with a neural connector and put an introspection module in a module slot.
**3)** Run the following code (can be done in the interactive lua shell)
`local modules = peripheral.find("neuralInterface")`
`local meta = modules.getMetaOwner()`

This bug really breaks Plethora, as `getMetaOwner` is very much an essential function and you can't do anything without it.

**Comment by SquidDev** [comment]
Which version of Minecraft is this for (and what refined storage version)? I'd guess they've changed their API.

**Comment by Tencao** [comment]
Minecraft 1.11.2
Refined storage - 1.4.20
Plethora - 1.1.7-pr0

**Comment by SquidDev** [comment]
I'm probably going to leave off uploading this to Curse for another couple of days, but [this download](https://www.dropbox.com/s/blqf5pvkb7zjn76/plethora-1.11.2-1.1.7-pr0.jar?dl=1) should fix it for now.
