### ISSUE TITLE
How do you use the CCTweaks Wireless Bridge with the Neural Interface?

### ISSUE THREAD

**Issue by r3Fuze** [SquidDev-CC/ccjam-2016#67]
This might not be the best place to ask, but I couldn't find any other place.

The [website](https://squiddev-cc.github.io/plethora/neural-interface.html) says it is compatible with the CCTweaks Wireless Bridge but I have tried everything I can come up with but can't combine them in any way.

If this is not possible then what is the best way to hook up a remote peripheral to the Neural Interface?

Minecraft: 1.10.2
ComputerCraft: 1.80pr0 from https://cc.crzd.me/
CCTweaks: 1.5.0-pr2
Plethora: 1.1.7-pr0

**Comment by SquidDev** [comment]
It _should_ be possible to place the wireless bridge in the peripheral slot of the neural interface, but apparently that is currently broken. I'll see what changed. Sorry.
