### ISSUE TITLE
1.10.2 Turtle auto reset 

### ISSUE THREAD

**Issue by Neekow** [SquidDev-CC/ccjam-2016#68]
Forge: 1.10.2-12.18.3.2185
CC: 1.80pr0-build12 (happends in build14 too)

What: The turtle completely reset, losing its label, peripherals and anything. Like i placed an all new crafted one
How: Running an excavate with a mining turtle
When: Randomly

So here's the problem, we can't do a thing with a turtle as it can reset anytime. Investigated a bit, seems to happens to moving turtle only, computers are safe. Tried to force the bug by unloading chunks, or avoid the bug by keep the chunk perma-loaded, still happening randomly.

**Comment by SquidDev** [comment]
This is a vanilla ComputerCraft bug, but I'm not entirely sure why it's happening - there isn't anything in CC's code which would result in this.

Can you try to reproduce this without Plethora and maybe report on the main CC issue tracker?
