### ISSUE TITLE
Issue with laser.fire()

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/ccjam-2016#7]
http://prntscr.com/bpfvue

Not entirely sure of the cause, although the script I was running is miningDrill.lua.

**Comment by SquidDev** [comment]
In your logs there should be a stack trace with the same message. Could you put it here? Thanks!

**Comment by inklit** [comment]
There does not seem to be any stack traces in the logs.

**Comment by SquidDev** [comment]
Ahhh. The method is a client only method. Curses. I'll fix this now.

**Comment by SquidDev** [comment]
Hrrrm. Are you sure there wasn't anything in the server logs? That is really odd.

**Comment by inklit** [comment]
I am 100% sure, if you would like I could give you the dev server package that I am testing with (although the world is HUGE, so you'd have to deal with creating a world on your own!)

**Comment by SquidDev** [comment]
Don't worry: my fault. `RuntimeException` was being caught but not other throwables. I'd forgotten that errors even exist _doh_.
