### ISSUE TITLE
Support for Blockcraftery ?

### ISSUE THREAD

**Issue by Yarillo4** [SquidDev-CC/ccjam-2016#73]
Blockcraftery is the spiritual successor of Carpenter's blocks

https://minecraft.curseforge.com/projects/blockcraftery

It adds framed blocks that can "contain" any block and use their texture plus some of their properties

I think it would be pretty cool if turtles were able to change the block inside (it's in a lot of modpacks). Unfortunately, it is not just a simple inventory

**Comment by SquidDev** [comment]
Sorry for the delay in getting round to this. I've added metadata support (so one can call `.getMetadata()` to find what block is currently inside it).

With respect to changing the internal block, I'm not sure the best way to approach this. I guess it would be possible to convert it to an inventory and expose it [as an inventory](https://squiddev-cc.github.io/plethora/methods.html#target-net-minecraftforge-items-iitemhandler). I don't know if you have any thoughts on the matter?

**Comment by Yarillo4** [comment]
Making it act like an inventory sounds like the most intuitive option. But you'd expose yourself to some complications if the mod author ever gets around implementing [Carpenter's safes](https://i.imgur.com/h0uCFSi.png) or really any sort of inventory

Also - I don't know how it's implemented but don't inventories handle some specific edge cases ? Maybe it'd be harder than anticipated ? Maybe you'd have to take into account things like swapping items with non-existent slots, sucking items out of an empty inventory, putting too many items in... 

I'd make specific methods for the peripheral - like "getTextureBlock" and "useAsTexture" to be safer

**Comment by SquidDev** [comment]
As elucent has said they're no longer maintaining Blockcraftery, I'm probably going to close this issue. If it get taken up again it's something I might look into again.
