### ISSUE TITLE
Chat not being intercepted on a sponge server

### ISSUE THREAD

**Issue by ihaveanaxe** [SquidDev-CC/ccjam-2016#78]
As I wrote above, my chat messages are not being intercepted when I issue them on SwitchCraft.
Code below.

```lua
local chat = peripheral.wrap("left")
chat.capture("^!give")
     
while true do
    local _, pattern, message, player, uuid = os.pullEvent("chat_capture")
    if pattern == "^!give" then       
        print("Not yet")
    end
end
```

**Comment by SquidDev** [comment]
This appears to be a sponge issue. I'll see if I can diagnose where the issue is on their end.

**Comment by SquidDev** [comment]
See https://github.com/SpongePowered/SpongeForge/issues/2002
