### ISSUE TITLE
Collision issues with sideways and upside down manipulators

### ISSUE THREAD

**Issue by BTCTaras** [SquidDev-CC/ccjam-2016#81]
If a manipulator is placed on a wall, at eye level, and you walk into its face, the entire screen gets covered up by the block's edge texture and you will be pushed out when you stop moving. You will be pushed back even if the manipulator is not at eye level. Walking into the air half of the side of a sideways manipulator will also push you back, which makes it seem at first glance as though it were a solid block.

Manipulators on the ground (facing up) aren't affected.

**Comment by BTCTaras** [comment]
It is possible to suffocate while walking into a sideways manipulator

**Comment by ihaveanaxe** [comment]
This also happens with wireless modems on computers.

**Comment by BTCTaras** [comment]
Wired and ender modems are not affected

**Comment by SquidDev** [comment]
OK, that's rather weird - the code _should_ be the same for all modems. Wired and ender modems are separate blocks (whilst wireless modems are part of the generic "peripheral" block), but they seem to return the same values for all the standard collision functions.

**Comment by BTCTaras** [comment]
Unlike sideways manipulators, wireless modems won't push you out of the block, but you'll take damage if you stand too close to either. I've made a mob grinder out of wireless modems, works really nicely

**Comment by SquidDev** [comment]
Important facts: `isFullBlock` and `isFullCube` do very slightly different things. See dan200/ComputerCraft#521 for the related CC fix.
