### ISSUE TITLE
Chat not being detected/sent but still being captured on SwitchCraft.

### ISSUE THREAD

**Issue by ihaveanaxe** [SquidDev-CC/ccjam-2016#82]
I'm able to capture chat, but not detect it via os.pullEvent("chat_capture") or os.pullEvent("chat_message") or use chat.say/chat.tell.
(Also, different bug, but, lasers fired by a manipulator/turtle do not break blocks or cause mobs to drop exp.)

**Comment by SquidDev** [comment]
I've been having no issues with the chat recorder, so more information would be appreciated: are you using it a neural interface or manipulator?, is it bound to the player?, etc...

> lasers fired by a manipulator/turtle do not break blocks 

Yeah, you can blame Sponge for that. It should be fixed on master, I just haven't had an opportunity to get a new release out.

**Comment by ihaveanaxe** [comment]
The chat recorder is inside a manipulator and is bound to me, I think the problem started around 1-2 days ago.
I've moved it inside and out of a claim, too.
(I'll launch and test with the neural manipulator soon and see if breaking and replacing the manipulator will help.)

**Comment by ihaveanaxe** [comment]
I’m sorry, it was some typos that I made in the code, and some strange code that caused it, sorry for wasting your time. (Thanks for fixing the laser related bugs though.)

**Comment by SquidDev** [comment]
Np problem - the block breaking bug is annoying me as much as anyone else :).
