### ISSUE TITLE
Coal put in furnace using Plethora only smelts 7 and 99/100 items.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/ccjam-2016#86]
When putting coal into furnace using Pelthora item movement functions it for some reason only smelts 7 and 99/100 items instead of 8 items. Smelting bar on last item almost reaches the end and then fuel ends and it falls back to 0,

Only happens if fuel is put inside using movement functions.
Happened on current Switchcraft.

**Comment by Wojbie** [comment]
When attempting to recreate the issue in SP interesing situation happends.

When attempting to call any function on furnace after it changes state from unlit to burning it errors with error: "The block has changed". This stops any program that has above issues from working at all in SP.

I do think there is something wierd going cause of furnace changing itself when it lights up.

**Comment by SquidDev** [comment]
With regards to the latter, [furnaces are horrible](https://github.com/SquidDev-CC/plethora/issues/34) [and evil](https://www.reddit.com/r/feedthebeast/comments/7zgfaa/mod_authors_while_working_on_your_mods_have_you/duo9rai/) and the best solution is to wait for 1.13.

**Comment by SquidDev** [comment]
I'm not able to reproduce the first on a single player world. Plethora doesn't do anything strange with inventories (it should be identical to placing it in with the GUI), so I'm just going to do my normal and blame sponge :p. Sorry :/.

**Comment by Wojbie** [comment]
Gotta love sponge. Welp smelting only 7 instead of 8 blocks per coal is a price of automation on sponge then I guess. Cheers and tx for taking a look.
