### ISSUE TITLE
Parrots don't have a rendered neural interface

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/ccjam-2016#88]
^^^
But how will it render? Like right on their eye/head?

**Comment by BTCTaras** [comment]
isnt that a cruel thing to do to those poor birbs

**Comment by SquidDev** [comment]
I need to rewrite the model injector system at some point, but this'll do for now.

![image](https://user-images.githubusercontent.com/4346137/36947711-aa6fcb8a-1fc7-11e8-87cc-9acb1cf0dc26.png)

**Comment by Jummit** [comment]
Looks good to me!
@BTCTaras I think you can blacklist parrots if you find them to cute (like me).
