### ISSUE TITLE
[1.12.2] Failed to load: org.squiddev.plethora.integration.appliedenergistics.MethodCraftItem

### ISSUE THREAD

**Issue by Morpheus1101** [SquidDev-CC/ccjam-2016#89]
Various errors in the fml-junk-earlystartup, i thought id whack up. Log @ https://gist.github.com/Morpheus1101/a13043f7bd5f869223be3096040f90d5

**Comment by SquidDev** [comment]
Fixed in 4834ba87ffed7c22c0a2bf9d15d3895e43cbc2c2. I'm hoping to get a release out in the next few days including this fix.
