### ISSUE TITLE
Neural Interface disappears when clicking Baubles ring

### ISSUE THREAD

**Issue by Ale32bit** [SquidDev-CC/ccjam-2016#90]
Neural Interface disappears when clicking Baubles ring button in the inventory while holding it.

I'm not sure if the bug is caused by Baubles or Plethora.

**Comment by SquidDev** [comment]
The neural interface doesn't do anything funky with the baubles API, so I suspect this is a Baubles bug. I'll have a look.

**Comment by Ale32bit** [comment]
Ok, thanks.

**Comment by SquidDev** [comment]
I'm unable to reproduce on Baubles 1.5.2 on a local client. I'm going to do my normal and blame Sponge :p.
