### ISSUE TITLE
Certain mobs don't die as if killed by player when using laser.

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/ccjam-2016#91]
As the title says, certain mobs die as if they were not killed by a player when the laser beam is attached to a manipulator or a turtle. This does not happen when the player has the laser equipped.

This doesn't affect passive mobs. It only affects neutral and hostile mobs that have not been aggro'd by a player. If a player attacks a neutral/hostile mob, then a laser finishes the mob off, it then counts as a player kill.

**Comment by Sascha-T** [comment]
Might want to check this out: https://github.com/SquidDev-CC/plethora/blob/3adb77541323114600c898cd80c85d1b40a7737c/src/main/java/org/squiddev/plethora/gameplay/modules/EntityLaser.java#L329

**Comment by SquidDev** [comment]
Fixed in 1832d64652e309973e6cae50e43cf89a28973b2d
