### ISSUE TITLE
Kinetic Augment Not Working, goodness-knows-03

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/ccjam-2016#92]
Upon using the kinetic augment, this error is thrown in the neural interface: 

![image](https://user-images.githubusercontent.com/35982013/37060933-b05a7586-2189-11e8-8aa8-21a315353d38.png)

**Comment by SquidDev** [comment]
99.7% sure this is a Sponge bug.

**Comment by SquidDev** [comment]
I'm unable to reproduce on latest Sponge. This should be what the server is running, so I've no clue what has gone wrong.

**Comment by SquidDev** [comment]
Unable to reproduce on the server. I suspect something went wrong when loading the server. I'll reopen if this occurs again.

**Comment by SquidDev** [comment]
And it happened again.
