### ISSUE TITLE
Entity Sensor returns diffirent lists for Turtle and for Computer.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/ccjam-2016#94]
When Entity Sensor is used to sense() by turtle it don't list players in results. Only Monsters/other entities.
When computer does sense() list contains all players in range.

Issue happens on current version of Switchcraft.

**Comment by SquidDev** [comment]
I'm pretty sure this is an issue with Sponge/GP: the entity sensor cannot find entities if you don't have permission to collide with them.
