### ISSUE TITLE
Insert Item

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#99]
Well, now that we have an export function for RS/AE, can we get import as well :)

Sorry, overlooked that when requesting export functionality.

**Comment by SquidDev** [comment]
I think you did, but I really wasn't sure what in would add beyond `.pushItem` into an interface. I'm not opposed to it, just not sure how it would look and behave.

**Comment by kepler155c** [comment]
For AE (in openperipheral versions), I would place the turtle on an
interface and have full access to crafting functions. For refined storage,
I believe the crafting is only available when connected to a controller. If
we had access to the crafting methods from the refined storage interface,
that would solve all issues.

Specifically, the interface would need to provide findItem, findItems, getCraftngTasks, listAvailableItems. Additional functions would be a bonus.

**Comment by SquidDev** [comment]
> Specifically, the interface would need to provide findItem, findItems, getCraftngTasks, listAvailableItems. 

I've fixed the RS integration so that all controller methods are also exposed on any other network block (interfaces, drives, etc...). I think this solves your issue, though correct me if I'm wrong.

> Additional functions would be a bonus.

Is there anything else you have in mind? I don't really use RS/AE, so I'm not sure what bits people wish to automate.

**Comment by kepler155c** [comment]
Beautiful... working perfectly

Tested AE and found an issue. I can access the controller methods from the interface (good), but findItem and findItems don't return correctly when passed a table. Example:

{
  count = 10,    -- this is normally ignored
  damage = 0,
  name = 'minecraft:dirt',
}

Passing in a string value of 'minecraft:dirt' does work correctly (but I would be unable to query damaged or items with NBT info).

**Comment by kepler155c** [comment]
AE is working - thx.
There are now better ways to determine the state of the requested crafting task but I will need to work on implementing that (previously you could specify which CPU to target). I'll let you know if there are any issues.
